### ISSUE TITLE
[Suggestion] Use hive for persistent storage.

### ISSUE THREAD

**Issue by iulian0512** [llfbandit/dio_cache_interceptor#10]
IMHO i think the sql+moor adds unnecessary complexity to the caching routine. Looking in the source repo i see that you mostly do single key search in the sqllite db to set/retrieve the cached response, for this particular use case hive is superior in all aspects.  Also hive works on web+mobile+desktop with no additional dependencies.

**Comment by llfbandit** [comment]
I agree, Hive could be a good candidate. At least on most used store calls.
No time for now to implement this. Are you able to provide a PR for this ?
I don't know much about Hive but it doesn't seem hard to add implementation with it.

My only concern is on `init()` and `initFlutter()` methods which should stay out of the API.
