### ISSUE TITLE
Support Dio 5

### ISSUE THREAD

**Issue by dokkaebi** [llfbandit/dio_cache_interceptor#109]
Dio has been updated to 5.0, and now version solving fails:

`Because dio_cache_interceptor 3.3.1 depends on dio ^4.0.0 and no versions of dio_cache_interceptor match >3.3.1 <4.0.0, dio_cache_interceptor ^3.3.1 requires dio ^4.0.0.`

**Comment by slavap** [comment]
https://github.com/llfbandit/dio_cache_interceptor/pull/103
