### ISSUE TITLE
How to use normal options and cached options together?

### ISSUE THREAD

**Issue by omidraha** [llfbandit/dio_cache_interceptor#11]
In `dio-http-cache` we have something like this:

```dart
Options cacheOptions = buildCacheOptions(Duration(days: 7), options: Options(
  headers: {
    'Accept-Language': 'en',
  },
));

Response response = await Dio().get("http://www.google.com", options: cacheOptions);

```

I try something like this:

```dart
CacheOptions cacheOptions = CacheOptions(
  maxStale: Duration(days: 7),
  store: DbCacheStore(databasePath: 'dio_cached'),
);

DioCacheInterceptor dioCacheManager = DioCacheInterceptor(options: cacheOptions);

Options options = cacheOptions.toOptions();
option.headers = {
  'Accept-Language': 'en',
};

dio.interceptors.add(dioCacheManager);


Response response = await dio.get(
	url
	options: options,
  );
```

**Comment by llfbandit** [comment]
I'm not sure to understand what you are trying to achieve with the given sample...

`CacheOptions` given to `DioCacheInterceptor` are the default cache options for each subsequent requests.
You don't need to repeat your configuration on each time.

**Comment by omidraha** [comment]
I would like to add some extra headers like this `'Accept-Language': 'en',` 
Where is the  correct place to add this header?

**Comment by llfbandit** [comment]
Just as you do normally:

```dart
dio.get(
  options: Options(
    headers: {
      'Accept-Language': 'en',
    },
));
```

**Comment by omidraha** [comment]
So with `CacheOptions` will be something like this:


```dart
CacheOptions cacheOptions = CacheOptions(
  maxStale: Duration(days: 7),
  store: DbCacheStore(databasePath: 'dio_cached'),
);

DioCacheInterceptor dioCacheManager =
	DioCacheInterceptor(options: cacheOptions);


dio.interceptors.add(dioCacheManager);


dio.get(
  options: Options(
    headers: {
      'Accept-Language': 'en',
    },
));
```

**Comment by omidraha** [comment]
> `CacheOptions` given to `DioCacheInterceptor` are the default cache options for each subsequent requests.
> You don't need to repeat your configuration on each time.

For some requests I need to use cache  and for some other requests I should not use cache.

**Comment by alr2413** [comment]
I think you need to manage it manually.
use a parameter like `shouldCache` for your request and then decide based on that if you wanna cache request or not.

**Comment by llfbandit** [comment]
@omidraha you mean you need to force no cache for a request that has directives?
If so, you use `CacheOption.noCache` for this specific request.
Otherwise, you don't need to do anything, if the response has no cache directives.
