### ISSUE TITLE
Update dio dependency to latest release

### ISSUE THREAD

**Issue by deeeznuds** [llfbandit/dio_cache_interceptor#110]
Update dio dependency to latest release.

**Comment by unacorbatanegra** [comment]
@llfbandit  thanks a lot for your contributions.
When do we can expect a release?
:)

**Comment by llfbandit** [comment]
Hopefully, when you'll wake up tomorrow morning!

**Comment by llfbandit** [comment]
Done.

**Comment by deeeznuds** [comment]
thank you very much!
