### ISSUE TITLE
Best Policy

### ISSUE THREAD

**Issue by kururu-abdo** [llfbandit/dio_cache_interceptor#111]
what is the best policy in case of :  just update cached when response is different from the cached otherwise return cached data?

**Comment by llfbandit** [comment]
If your origin server has cache directives just use `CachePolicy.request`, this is the default behaviour.

**Comment by kururu-abdo** [comment]
excuse me .
last question:

when there is no internet what is the best policy?

@llfbandit

**Comment by llfbandit** [comment]
I can't take this decision for you.
The package provides offline capability by enabling `hitCacheOnErrorExcept: [...]`
