### ISSUE TITLE
Caching doesn't work as I expect

### ISSUE THREAD

**Issue by deeeznuds** [llfbandit/dio_cache_interceptor#112]
Hi!
I have dio_cache_interceptor_hive_store in my project. Also from the backend, I've set up settings for the cache in response headers:
ETag (for files)
last-modified: [Wed, 01 Mar 2023 05:54:26 GMT]
date: [Wed, 01 Mar 2023 08:35:22 GMT]
cache-control: [max-age=86400, public, must-revalidate, proxy-revalidate].

But caching actually doesn't work as I expect. I have several endpoints where I want to save data to the cache store and where I don't.
In my case, CachePolicy.request - saves all responses, even if they don't have cache control in headers. Other cache policies don't cache data at any response.

Please help with settings for caching.

**Comment by llfbandit** [comment]
`cache-control` header is not mandatory to allow client data caching.

For example, if the origin server sets `etag`, the client will save the response in cache.
Next time, the client will request the origin server against the previous etag and react accordingly to the response:
- 200, the client will save the new response.
- 304, the client will update only the returned headers and serve the cached data to the app. The origin server should not return any body in the response.

**Comment by deeeznuds** [comment]
> `cache-control` header is not mandatory to allow client data caching.
> 
> For example, if the origin server sets `etag`, the client will save the response in cache. Next time, the client will request the origin server against the previous etag and react accordingly to the response:
> 
> * 200, the client will save the new response.
> * 304, the client will update only the returned headers and serve the cached data to the app. The origin server should not return any body in the response.

ETag is only for files, but what if I want cache responses with not type of file, for example: map, list, string, int ?
I think the better solution for cache trigger is cache-contol filed in headers.

**Comment by llfbandit** [comment]
Etag may be tied to files in your case but for others.
I provided you this as an example you can replace it by any header you want, your question is more related to how HTTP cache works.

From here there is still no relationship with the package.

**Comment by deeeznuds** [comment]
@llfbandit how I can cache non-file type responses? For example, the endpoint returns List<String>, but it hasn't ETag property because it is not a file, nginx can not set ETag for this endpoint.
