### ISSUE TITLE
当内容改变的时候，如果去强制使用服务器的内容而不是缓存

### ISSUE THREAD

**Issue by desire0420** [llfbandit/dio_cache_interceptor#113]
当内容改变的时候，如果去强制使用服务器的内容而不是缓存，
场景：有一个列表 点击显示详情，当我点击加载后，再有效期内服务器内容改变了，我如何去设置强制使用服务器的内容

**Comment by llfbandit** [comment]
Official language is English here, french also if you want.

**Comment by easyandroid-cc** [comment]
中文，加油
