### ISSUE TITLE
Caching Does Not Work

### ISSUE THREAD

**Issue by Igorkoff** [llfbandit/dio_cache_interceptor#115]
Hello,

I hope you are doing well. I would like to use dio_cache_interceptor to cache JSON data from an API when my phone is offline (previously used dio_http_cache and it worked, but it was having conflicts with other dependencies because it's so obsolete).

I had a look at similar issues, but still could not get my code to work.

Here's my code in losses.dart: 

```
Future<Details> fetchDetails(Dio dio) async {
  dio.interceptors.add(DioCacheInterceptor(
      options: CacheOptions(
    store: MemCacheStore(),
    policy: CachePolicy.refresh,
    priority: CachePriority.normal,
    hitCacheOnErrorExcept: [],
  )));
  Response response = await dio.get('https://russianwarship.rip/api/v1/statistics/latest');

  if (response.statusCode == 200) {
    return Details.fromJson(response.data);
  } else {
    throw Exception('Failed to Load Details');
  }
}
```

And this is a snippet from the losses_page.dart:

```
Future<Details>? futureDetails;
  Dio dio = Dio();

  @override
  void initState() {
    super.initState();
    futureDetails = fetchDetails(dio);
  }

  @override
  void dispose() {
    super.dispose();
    dio.close();
  }
```

When the phone is online, the data from the API is being displayed on the page, however, when it is offline:

```
flutter: DioError [DioErrorType.other]: SocketException: Failed host lookup: 'russianwarship.rip' (OS Error: nodename nor servname provided, or not known, errno = 8)

flutter: Source stack:
flutter: #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
flutter: #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
flutter: #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
flutter: #3      fetchDetails (package:tank_hunter/domain/losses.dart:14:33)
```

Thank you very much in advance for your help.

**Comment by llfbandit** [comment]
You are using wrong policy for your usage:

```dart
  /// Requests regardless cache availability.
  /// Caches if response has cache directives.
  refresh,
```

You should use `request` for conventional cache.
If you're using client only mecanism go read the docs for other policies and/or options.

**Comment by Igorkoff** [comment]
Thank you very much for your quick reply. Also, the problem seems a bit similar to [this issue](https://github.com/llfbandit/dio_cache_interceptor/issues/20). I've just changed the policy to request, but the issue is still there. 

Yeah, essentially I would like my client to cache the JSON data locally that I get from a third-party API for 24 hours and I don't think that it is using any directives.

**Comment by llfbandit** [comment]
Please have a look at https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only
