### ISSUE TITLE
Cannot update forceCache value when there is no http directive

### ISSUE THREAD

**Issue by alr2413** [llfbandit/dio_cache_interceptor#12]
first, special thanks for providing this awesome package.

i'm using the following line in my app because i want to toggle between cache value or update it.
```
policy: forceRefresh ? CachePolicy.refresh : CachePolicy.forceCache,
```
The problem is that the cache value which is stored by forceCache in DBStore is never getting updated even if i set the cache policy to refresh (there is no cache directive in header).

do you have a solution?

**Comment by llfbandit** [comment]
Hmm, there's a hole here. Thanks for the report!
You can't use `CachePolicy.refresh` as this policy follows HTTP directives.

As a workaround, and what should be done internally, you could directly access to the cache store by re-creating RequestOption to get the key and delete the entry, this a little boring.
So, I'll make another policy `CachePolicy.refreshForceCache` to cover this case and finally get parity with `CachePolicy.refresh` and `CachePolicy.request`.

**Comment by alr2413** [comment]
Ok, thanks.
when do you implement that?

**Comment by llfbandit** [comment]
On it!

**Comment by llfbandit** [comment]
Version 2.1.1 uploaded. Can you confirm the fix with refreshForceCache new policy?

**Comment by alr2413** [comment]
yea, i'll check now.

**Comment by alr2413** [comment]
thanks a lot.
it's working well.
