### ISSUE TITLE
Cache with 304 (no content) example?

### ISSUE THREAD

**Issue by vicenterusso** [llfbandit/dio_cache_interceptor#123]
Hello,

I'm not finding any example dealing with 304 with no content. (being it validated as error or not)

I tried client only cache but I don't think this is what I need,  cant rely on client only. I *need* to know if server returns 304.

I think the main problem is the fact that 304 returns no content. Shouldn't this package "fill" response.data if cache is present with 304?

I can't change server response to 200 (with full response + etag).

Any ideais to handle this basic scenario?

```dart
final response = await dio.get('/my-url'); //status 304 

if (response.data.isEmpty) { // <-- having exception on this, response is null

}
```

**Comment by vicenterusso** [comment]
Sorry, but how the example help with the issue?

Questioning again:

Shouldn't this package "fill" response.data if cache is present with 304?

**Comment by vicenterusso** [comment]
So, I'm having response.data `null`. Can you help me to find the source of the null result? Where in the code it looks for the database? I'm using Hive btw

![image](https://github.com/llfbandit/dio_cache_interceptor/assets/80538/ac673f23-2d9e-49ba-8f80-05169ce5ae34)

**Comment by llfbandit** [comment]
Please fill a reproducer in another issue to clearly identify your problem.

**Comment by ryzr** [comment]
Just FYI, had the same thing:
```
final cacheResponse = await cacheStore.get(CacheOptions.defaultCacheKeyBuilder(response.requestOptions));
```

The result of this showed me I actually have a 304 response with null content stored in the cache. This is likely due to adding 304 to the allowed statuses 

```
validateStatus: (int? status) {
    return status != null && ((status >= 200 && status < 300) || status == 304);
}))
```

Currently in the process of figuring out if theres a trick to 
1. not overwrite valid cached responses with a 304 response with null content
2. avoid the error "DioError [bad response]: The request returned an invalid status code of 304"

**Comment by vicenterusso** [comment]
> EDIT: I found I no longer need validateStatus. I did have some onError interceptors which I moved after the DioCacheInterceptor, which seems to have resolved my issues.

Your cache interceptor is the first in the list? I have few other interceptors (adding token, logging, etc)
