### ISSUE TITLE
[Question] HiveError: Could not read value from box. Maybe your box is corrupted.

### ISSUE THREAD

**Issue by AndreHaueisen** [llfbandit/dio_cache_interceptor#124]
Hi. I'm getting this exception in production, but I can't figure out why it is happening and I haven't been able to reproduce it in dev. Do you have any insights into when this exception is thrown?

![Screenshot 2023-06-02 at 10 02 33](https://github.com/llfbandit/dio_cache_interceptor/assets/13854934/9682df07-51a1-45b6-a501-f2bfdfc76d36)

It appears it happens when line 49 tries to access my box.

![Screenshot 2023-06-02 at 10 07 16](https://github.com/llfbandit/dio_cache_interceptor/assets/13854934/3bcd342c-78bc-4a4e-a9ed-50f08ac8a635)

I'd appreciate any tips you think might be relevant.

**Comment by llfbandit** [comment]
Unfortunately I really don't know. Maybe you should ask to Hive maintainers?

**Comment by AndreHaueisen** [comment]
All good. Thank you!
