### ISSUE TITLE
how to use forceRefresh like Get data from network first If getting data from network succeeds, store or refresh cacheIf getting data from network fails or no network avaliable, try get data from cache instead of an error.

### ISSUE THREAD

**Issue by YounesKHENIFER** [llfbandit/dio_cache_interceptor#129]
i wonder how to use forceRefresh like 

Get data from network first.
If getting data from network succeeds, store or refresh cache.
If getting data from network fails or no network avaliable, try get data from cache instead of an error.

i tried  CachePolicy.refreshForceCache and  CachePolicy.refresh not working form me and not using the cache if there is network issue

**Comment by llfbandit** [comment]
Use `hitCacheOnErrorExcept` to handle network failures.

**Comment by YounesKHENIFER** [comment]
> hitCacheOnErrorExcept

thanks i have added 304 and its working !
