### ISSUE TITLE
App crashes when data of response is null 

### ISSUE THREAD

**Issue by yzTabcorp** [llfbandit/dio_cache_interceptor#132]
We are facing same issue of this thread: https://github.com/llfbandit/dio_cache_interceptor/issues/125. We have captured crashes in firebase crash report in prod app and we can't close those crashes if they haven't been addressed.  Attached the track log of those crashes below:
```
.serializeContent (content_serialization.dart:11)
CacheResponse.writeContent (cache_response.dart:260)
DioCacheInterceptor._saveResponse (dio_cache_interceptor.dart:212)
DioCacheInterceptor.onResponse (dio_cache_interceptor.dart:93)
```

Please help on fixing this issue in coming versions. Thanks!

**Comment by llfbandit** [comment]
Fixed in 3.4.3
