### ISSUE TITLE
uuid: ^4.0.0

### ISSUE THREAD

**Issue by LastMonopoly** [llfbandit/dio_cache_interceptor#134]
Hi @llfbandit 

Is it ok to upgrade dependencies from uuid: ^3.0.7 to uuid: ^4.0.0?

Thanks a lot

**Comment by llfbandit** [comment]
Thanks for the report.
UUID v4 is compatible with v3 for this package, so UUID v4 aside v3 is now allowed in dio_cache_interceptor 3.4.4.
