### ISSUE TITLE
Async requests are not being cached

### ISSUE THREAD

**Issue by oSumAtrIX** [llfbandit/dio_cache_interceptor#135]
This issue may not belong in this repo but in DIO.

# Issue

The cache interceptor saves the response to the cache in the `onResponse` implementation. When I make 2 identical requests asynchronously but do not read the response yet, both requests will not be caught by the cache. I assume the reason for this is that the 2 requests were made at the time when the cache was not present, because `onResponse` has not been called yet.

# Observations

- Using a breakpoint at https://github.com/revanced/revanced-manager/blob/f905a529887f7e6025cad7392823780bf589a6ce/lib/services/revanced_api.dart#L71C1-L71C1: The line is being called multiple times, but the line below that reads the response is not being hit, presumably, because the request is made asynchronously.
- Using an HTTP debugger: The `/tools` endpoint is not being cached. 

# Reproduction

You can reproduce this issue on our repository: https://github.com/revanced/revanced-manager.

- Adding the interceptor: https://github.com/revanced/revanced-manager/blob/f905a529887f7e6025cad7392823780bf589a6ce/lib/services/revanced_api.dart#L31
- Making the request (this is called multiple times asynchronously): https://github.com/revanced/revanced-manager/blob/f905a529887f7e6025cad7392823780bf589a6ce/lib/services/revanced_api.dart#L71C1-L71C1

**Comment by llfbandit** [comment]
`QueuedInterceptorsWrapper` may help to resolve this.
The original issue https://github.com/cfug/dio/issues/590

Here's an example (untested):

```dart
    final cache = DioCacheInterceptor(options: cacheOptions);

    dio = Dio()
      ..interceptors.add(
        QueuedInterceptorsWrapper(
          onRequest: cache.onRequest,
          onResponse: cache.onResponse,
          onError: cache.onError,
        ),
      );
```

**Comment by oSumAtrIX** [comment]
Unfortunately, this had no effect. But I assume this is the wrong repository. Thanks.
