### ISSUE TITLE
Getting empty data from cache

### ISSUE THREAD

**Issue by realchandan** [llfbandit/dio_cache_interceptor#136]

**Comment by llfbandit** [comment]
I tried to reproduce this with this URL: https://media1.giphy.com/media/sG8gmIFd6G7xHdQE9y/200.gif

In the response, we get:
cache-control: no-store, private, max-age=0, no-cache, must-revalidate, s-maxage=0

This is why the cache store is empty.

If you want to force cache, you must use the dedicated policies and handle it by yourself.
