### ISSUE TITLE
Not working on web 

### ISSUE THREAD

**Issue by cavin-7span** [llfbandit/dio_cache_interceptor#138]
I have added this package to cache API calls but it seems that this is not working for web since Flutter web doesn't allows us to use path_provider. Here's my implementation that I'm using right now:

```dart
final dir = await getTemporaryDirectory();
      final options = CacheOptions(
        store: HiveCacheStore(dir.path),
        hitCacheOnErrorExcept: [401, 403],
      );

      /// Adding caching interceptor for request
      dio.interceptors.add(DioCacheInterceptor(options: options));
```

**Comment by cmengler** [comment]
For web, set the directory to null as it's not applicable -- e.g. `HiveCacheStore(null);`

**Comment by jaredsburrows** [comment]
@cavin-7span @cmengler So Hive works on flutter for web? What about IsarCacheStore? It only takes a non null String.
