### ISSUE TITLE
[Feature] Support GetStorage as a caching mechanism.

### ISSUE THREAD

**Issue by jlambright** [llfbandit/dio_cache_interceptor#139]
Is there any chance we could see support for [GetStorage](https://pub.dev/packages/get_storage)?

**Comment by llfbandit** [comment]
Sorry no, you could achieve the very same thing with `MemCacheStore`, `FileCacheStore` and `BackupCacheStore`.
The main problem with GetStorage is there's no strategy to limit data into memory.
