### ISSUE TITLE
Why is the expiration time set by maxStale in CacheOptions ineffective?

### ISSUE THREAD

**Issue by andrew2558** [llfbandit/dio_cache_interceptor#145]
Why is the expiration time set by maxStale in CacheOptions ineffective? The configured time is Duration(minutes: 5), but even after exceeding the expiration time, data is still retrieved from the cache without requesting the API. Is this caused by a timezone issue?

<img width="441" alt="Screenshot 2024-03-14 at 15 38 46" src="https://github.com/llfbandit/dio_cache_interceptor/assets/25080605/cb5f1e5f-6b90-494f-876a-6cb781f36bcd">

```dart
class DioCacheOptions {
  static MemCacheStore appMemCacheStore = MemCacheStore();
  static Future<CacheOptions> getCacheOptions() async {
    return CacheOptions(
      store: appMemCacheStore,
      policy: CachePolicy.forceCache,
      maxStale: AppConfig.cacheStorageTime,
      hitCacheOnErrorExcept: [],
      priority: CachePriority.normal,
      keyBuilder: (request) {
        return request.uri.toString();
      },
    );
  }
}
```

dio config:
```dart
cacheOptions = await DioCacheOptions.getCacheOptions();
dio.interceptors.add(DioCacheInterceptor(options: cacheOptions));
```

**Comment by llfbandit** [comment]
Did you try with this setup?
https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only#maxstale-postponing-or-not

**Comment by Yumikolab** [comment]
这个问题解决了嘛

**Comment by Yumikolab** [comment]
> 你试过这个设置吗？ [https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only#maxstale-postponing-or-not ](https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only#maxstale-postponing-or-not)

这个我试过了，如果是forceCache，则直接不会经过InterceptorsWrapper的onRequest方法

**Comment by Yumikolab** [comment]
> 你试过这个设置吗？ [https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only#maxstale-postponing-or-not ](https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only#maxstale-postponing-or-not)

如果是Request policy，则不会缓存

**Comment by andrew2558** [comment]
@llfbandit thanks.
Does this mean maxStale is a rolling time window? If maxStale is set to 10 minutes, after the first request, if there are no identical requests, the cached data will expire after 10 minutes. However, if the same request is made again after 10 minutes, the data will be fetched from the backend API. If a request is made again 5 minutes after the first request, the data will be retrieved from the cache, and the expiration time of the cached data will be updated to the current request time plus maxStale time, is that correct?
So, is it correct to understand that maxStale is a rolling time window?

**Comment by llfbandit** [comment]
It can be. It's up to you. Since `maxStale` is dedicated to handle cache from client only, there's no single rule to handle your cache.
This is why I let this door open.

**Comment by andrew2558** [comment]
get it 
thank you very much @llfbandit
