### ISSUE TITLE
HiveCacheStore on no local info

### ISSUE THREAD

**Issue by oscarshaitan** [llfbandit/dio_cache_interceptor#146]
I spot that using CachePolicy.request and the HiveCacheStore when hive don't have any value to return, the call never get resolved even if the network one is working any potential  work around? or Im understanding the plicies wrong?

**Comment by llfbandit** [comment]
The call should complete anyway. Don't you have any error in log? How did you setup Hive?

**Comment by oscarshaitan** [comment]
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/66c9d150-5698-4f8f-a89a-853c66a02444)
 I just extended to put some logs and try to throw an error 
 
 and forthe options
 
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/40607bb1-e947-4b6a-8b37-46f800f2302e)

**Comment by llfbandit** [comment]
If you throw an exception when there's no cached response, this is your issue. Just return whats coming from `super`.

**Comment by oscarshaitan** [comment]
I put that throw while I was testing but even with 
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/0da55b52-2afe-4600-9897-1d9afb9f85da)
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/0f588c51-2356-415a-8ede-8ef5d3e24785)
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/42f49f02-cf3d-4fea-9938-8762f43caceb)


the app got stuck there because the on request is doing nothing

**Comment by oscarshaitan** [comment]
doing more debug
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/fb5b1ccb-b26d-4ba7-a01b-68b172eb4f68)
( dio_cache_interceptor.dart)gets here but never reach the next handler
![image](https://github.com/llfbandit/dio_cache_interceptor/assets/9093952/d1f3fb58-0c2c-4c59-910b-0a77cee57185)
the reason is this value is null  in cache_response.dart line 239

**Comment by oscarshaitan** [comment]
I spot my issue, I was assuming that the Dio.get will always return and in this case returns null
