### ISSUE TITLE
Cache for Paginated API

### ISSUE THREAD

**Issue by skybur** [llfbandit/dio_cache_interceptor#15]
My app has a list which supports pagination with data loaded from API call and I also cached the data.
In that list I also implemented pull to refresh function to force refresh the data from server. 
When I trigger the pull to refresh, only the first page is loaded from server, and next page is returned from cache.
Is there any way for subsequent API call which only differs in page & size to not load from cache? Can I delete cache which has same URL but different query params?

I implemented a custom Dio client for force refresh trigger. When I trigger the pull to refresh I set the forceRefresh to true.
```dart
class CustomDio extends DioForNative {
  final CacheOptions _cacheOptions;
  CustomDio([
    BaseOptions options,
    this._cacheOptions,
  ]) : super(options);

  /// Set Caching Options
  ///
  /// [forceRefresh] will determine the response is coming from cache if available or network request
  ///
  /// [maxAge] will determine cache will be deleted
  void setCacheOptions({
    bool forceRefresh = true,

    /// Duration until cache deleted
    Duration maxAge = const Duration(minutes: 30),
  }) {
    final cache = _cacheOptions
        .copyWith(
          policy: forceRefresh ? CachePolicy.noCache : CachePolicy.forceCache,
          maxStale: maxAge,
        )
        .toOptions();
    options.extra.addAll(cache.extra);
  }
}
```

I hope this is clear enough to understand. Thank you.

**Comment by llfbandit** [comment]
You can directly access to your store and delete manually the entries.
Caveat, `RequestOptions` request has to be re-created manually or you can create your own interceptor inserted before `DioCacheInterceptor` for cleaner code.

Here's a minimal sample for store manipulation:

```dart
CacheOptions options = ...;
final cacheKey = options.keyBuilder(request); 
await options.store.delete(cacheKey);
```

Also, you can setup your own keyBuilder but I'm not sure if the target reachable with this method.

**Comment by skybur** [comment]
Thanks for the fast response. 

I actually considered to use custom keybuilder but after I looked at the source code it seems saving and deleting the cache used exact match of key, so if I make the key builder to use only the URL without query params, the cache will be overwritten for the same URL (CMIIW)

Is it possible to add condition parameter (matching predicate) for key when deleting cache? 
For example, I have called these APIs and their responses are cached
```
https://example.com/api/list?page=1
https://example.com/api/list?page=2
https://example.com/api/list?page=3
```
then when I want to delete the cache for all page I call this method
```dart
store.deleteWhere((key) => key.contains('api/list'));
```

**Comment by llfbandit** [comment]
To do this, implement the first method provided. I don't see other option.
Generic HTTP caching is a bit weak when paginating.

**Comment by skybur** [comment]
Ah alright then, will do that. Thanks for responding 😄
