### ISSUE TITLE
How to delete all cached data with the same API but different parameters (such as data loaded with pagination) from the cache?

### ISSUE THREAD

**Issue by andrew2558** [llfbandit/dio_cache_interceptor#150]
if pagination is used to load data, the API requests are like this: `getdata?page=1, getdata?page=2`, and so on. How can we delete the cached data with the same API but different parameters, so that subsequent requests for the same API do not use the cache but fetch data from the backend instead?

**Comment by llfbandit** [comment]
I'm not sure to understand fully your request.
You can access directly to your store and handle the deletion.

Please use discussion feature for such topics.

**Comment by llfbandit** [comment]
Read the documentation for `CacheStore`, there's `deleteFromPath` that should do it.
