### ISSUE TITLE
Switch dio_cache_interceptor_isar_store to use community managed Isar fork of isar_flutter_libs (AGP namespace issue)

### ISSUE THREAD

**Issue by tristanatdexcom** [llfbandit/dio_cache_interceptor#153]
We can't use the isar store from this package because its dependency (isar_flutter_libs) has outdated code that is incompatible with the latest AGP. It looks like there's already a PR opened in Isar to make the fairly easy changes, but someone commented to check out the community fork since it's unlikely the PR would get merged in any time soon due to the person maintaining it being pretty much MIA.

They've already added the required namespace code to the community managed fork, so given their active maintenance, for now it might be the better option for any isar features in this package.

**Comment by llfbandit** [comment]
What can be done here is to fill a PR or add dependency override on your side.
