### ISSUE TITLE
Make clear DB on open optional

### ISSUE THREAD

**Issue by beerline** [llfbandit/dio_cache_interceptor#156]
Thank u for such a useful library!

This library can be used for offline mode if make clean db on open optionally. 

## How it is implemented now
each time on db open plugin clears db (at least isar implementation)

## Proposal feature
make clear db on open db optional

**Comment by llfbandit** [comment]
DB is only cleared from obsolete entries

**Comment by beerline** [comment]
@llfbandit isar clearing on open

https://github.com/llfbandit/dio_cache_interceptor/blob/c73e8950fc98ae2924b6d4169c3ff2c6d9819466/dio_cache_interceptor_isar_store/lib/src/store/dio_cache_interceptor_isar_store.dart#L168
