### ISSUE TITLE
Don't support post request cache?

### ISSUE THREAD

**Issue by masonTool** [llfbandit/dio_cache_interceptor#16]
caused by the hard code

```
static const String _getMethodName = 'GET';
```

**Comment by llfbandit** [comment]
Sorry, no as it is fuzzy and likely inefficient to fingerprint bodies in most cases.
What's your use case, SOAP requests ?

**Comment by NamanShergill** [comment]
> Sorry, no as it is fuzzy and likely inefficient to fingerprint bodies in most cases.
> What's your use case, SOAP requests ?

Graphql requests are POST requests, and some responses can potentially have cache control headers as well. Maybe make it optional to cache POST requests, which defaults to false, if it's possible?

**Comment by llfbandit** [comment]
Now available in 2.3.0
