### ISSUE TITLE
StorageBackendVm.compact OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by kaciula** [llfbandit/dio_cache_interceptor#163]
I'm getting plenty of crash reports from both ios and Android devices in the form of:

`PathNotFoundException: Cannot rename file to '/var/mobile/Containers/Data/Application/09DF1AE1-074B-43F4-BA47-ACFE3D1B0350/Documents/cache/dio_cache.hive', path = '/var/mobile/Containers/Data/Application/09DF1AE1-074B-43F4-BA47-ACFE3D1B0350/Documents/cache/dio_cache.hivec' (OS Error: No such file or directory, errno = 2)

0  ???                            0x0 _File.rename.<fn> (dart:io)
1  ???                            0x0 StorageBackendVm.compact.<fn> + 188 (storage_backend_vm.dart:188)`

I'm not sure what's going on as I can't reproduce this on my devices.

**Comment by llfbandit** [comment]
Somehow the database is deleted. Maybe by your app, the user or the system if it run out of storage space.
Ensure your path is not one that could be managed by the OS.

Closing as this is not related to the package.

**Comment by kaciula** [comment]
@llfbandit I don't believe it's the case. The path used is the same one used by the Hive package. It's inside the Documents directory. I have never had any issue with the main Hive database disappearing.

Looking at the failing code, if I understand this correctly, the cache database is found and is being compacted but then it fails when it is being renamed.

**Comment by llfbandit** [comment]
So I guess this is more an issue for hive or hive_ce when migrated.
This package does not run this instruction.
