### ISSUE TITLE
Why can't some get requests be cached and some can

### ISSUE THREAD

**Issue by KaiLiDev** [llfbandit/dio_cache_interceptor#165]
I use the following configuration in my code to achieve this effect, requesting if there is a network and using caching if there is no network, as follows:
   _dio.interceptors.add(DioCacheInterceptor(
        options: CacheOptions(
            // store: MemCacheStore(),
            hitCacheOnErrorExcept: [401, 403, 404],
            // for offline behaviour
            policy: CachePolicy.request,
            priority: CachePriority.normal,
            store: FileCacheStore(value.path),
            maxStale: const Duration(days: 7),
            allowPostMethod: true),
      ));
But I've found that some get requests can be cached, and some can't, unless the forceCache mode is used; Is there a problem with my usage? Thanks to anyone who helped me out

**Comment by llfbandit** [comment]
It all depends of the dedicated server. If the server has cache directives the package will react accordingly.

**Comment by KaiLiDev** [comment]
> It all depends of the dedicated server. If the server has cache directives the package will react accordingly.

Can I use DioCacheIntercepter to maintain cache locally when the server has no cache instruction? If there is a network, use the network; otherwise, use the local cache;

**Comment by KaiLiDev** [comment]
> > It all depends of the dedicated server. If the server has cache directives the package will react accordingly.
> 
> Can I use DioCacheIntercepter to maintain cache locally when the server has no cache instruction? If there is a network, use the network; otherwise, use the local cache;

Thanks for asking if there is a plug-in that meets this requirement if DioCacheInterceptor does not support it.
