### ISSUE TITLE
(moor): It looks like you've created the database class DioCacheDatabase multiple times.

### ISSUE THREAD

**Issue by ericel** [llfbandit/dio_cache_interceptor#17]
How to solve the below error since I am not directly adding moor to my app?

```
flutter: WARNING (moor): It looks like you've created the database class DioCacheDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database.
Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
Here is the stacktrace from when the database was opened a second time:
#0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:88:30)
#1      new GeneratedDatabase (package:moor/src/runtime/api/db_base.dart:59:12)
#2      new _$DioCacheDatabase (package:dio_cache_interceptor/src/store/db_cache_store/database.g.dart:237:41)
#3      new DioCacheDatabase (package:dio_cache_interceptor/src/store/db_cache_store/database.dart:10:39)
#4      openDb (package:dio_cache_interceptor/src/store/db_cache_store/db_platform/db_os.dart:16:10)

```

**Comment by llfbandit** [comment]
```dart
await cacheStore.close();
```

Will close the underlying database.

**Comment by NamanShergill** [comment]
> 
> 
> How to solve the below error since I am not directly adding moor to my app?
> 
> ```
> flutter: WARNING (moor): It looks like you've created the database class DioCacheDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database.
> Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
> Here is the stacktrace from when the database was opened a second time:
> #0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:88:30)
> #1      new GeneratedDatabase (package:moor/src/runtime/api/db_base.dart:59:12)
> #2      new _$DioCacheDatabase (package:dio_cache_interceptor/src/store/db_cache_store/database.g.dart:237:41)
> #3      new DioCacheDatabase (package:dio_cache_interceptor/src/store/db_cache_store/database.dart:10:39)
> #4      openDb (package:dio_cache_interceptor/src/store/db_cache_store/db_platform/db_os.dart:16:10)
> ```

Best way would be to create a single object on app startup and add a reference to that in the CacheOptions instead of creating a new object there.

```dart
CacheOptions(
    store: Global.cacheStore)
```

instead of

```dart
CacheOptions(
    store: DbCacheStore(databasePath: path))
```

**Comment by ericel** [comment]
Thanks @NamanShergill. From your answer above, what would the Global.cacheStore hold? Sounds to me like just a variable carrying the same old store options. is it not?

**Comment by NamanShergill** [comment]
> Thanks @NamanShergill. From your answer above, what would the Global.cacheStore hold? Sounds to me like just a variable carrying the same old store options. is it not?

It's basically a getter for a DbCDbCacheStore object that's initialised at app startup, you should only initialise it once in the app and call that object anywhere you need it, doing it directly in the dio wrapper will make a new instance everytime there's an API request, which is what that error is about.

**Comment by ericel** [comment]
@NamanShergill 
So this is my present setup
I have a function:
```
  Future<void> setCachemanager() async {
    /// Sets Cache Manage database store
     Dio dio = Dio();
     final dir = await  pp.getApplicationDocumentsDirectory();
     print(dir);
    // Global Cache options
    var options = CacheOptions(
      store: DbCacheStore(databasePath: dir.path, databaseName: 'appmy-db', logStatements: true), // Required.
      policy: CachePolicy.request, // Default. Checks cache freshness, requests otherwise and caches response.
      hitCacheOnErrorExcept: [401, 403], // Optional. Returns a cached response on error if available but for statuses 401 & 403.
      priority: CachePriority.normal, // Optional. Default. Allows 3 cache sets and ease cleanup.
      maxStale: const Duration(days: 7), // Very optional. Overrides any HTTP directive to delete entry past this duration.
    );

   return dio.interceptors.add(DioCacheInterceptor(options: options));

  }

```
Then , I call this on the main.dart as init function:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initializes App With Services
  await setCachemanager() ;

  // Run Flutter App
  runApp(...
}
```
That creates the store.
How do I get these options, so I can pass with a dio request as you mentioned as an object?
// Add cache interceptor with global/default options
```
final dio = Dio()
  ..interceptors.add(DioCacheInterceptor(options: options),
```
Sorry for the inconvenience.

**Comment by NamanShergill** [comment]
@ericel 

```dart
class Global {
  static String? _directoryPath;
  static DbCacheStore? _cacheStore;
  static DbCacheStore get cacheStore => _cacheStore!;

  static Future setupAppCache() async {
    await getApplicationDocumentsDirectory()
        .then((value) => _directoryPath = value.path);
    _cacheStore = DbCacheStore(databasePath: _directoryPath!);
  }
}
```
You call `Global.setupAppCache()` on app startup.

And then you can call `Global.cacheStore` where you're providing a cache store to the wrapper.

**Comment by ericel** [comment]
@NamanShergill 
Thank you.
That gives me the following error:
Failed assertion: line 22 pos 16: 'options.store != null': is not true.

**Comment by NamanShergill** [comment]
> @NamanShergill 
> Thank you.
> That gives me the following error:
> Failed assertion: line 22 pos 16: 'options.store != null': is not true.

Did you forget to provide the store to the interceptor? The snippet I gave you has the store getter he non nullable so if it was null you would've received an error before the assertion could have been reached.

**Comment by ericel** [comment]
@NamanShergill  Got it working. Thanks alot.
