### ISSUE TITLE
Cache-Control with max-age is not cached

### ISSUE THREAD

**Issue by vicanso** [llfbandit/dio_cache_interceptor#18]
I found that `Cache-Control: public, max-age=604800, immutable` is invalid. The max-age should be 604800, but it does not work。I must use `Cache-Control: public`,`Cache-Control: max-age=604800`, `Cache-Control: immutable`. Is this a bug?

https://github.com/llfbandit/dio_cache_interceptor/blob/2ae551012c3cf7d6f208cd7ede394261be9e706f/lib/src/model/cache_control.dart#L30

**Comment by llfbandit** [comment]
Thanks for the report!
You're right, Dio does not expand comma separated values (anymore?).
This issue should be addressed to dio package also, I'll make a fix to handle this.

**Comment by llfbandit** [comment]
Published in version 2.3.1.
