### ISSUE TITLE
caching not working.

### ISSUE THREAD

**Issue by jigarfumakiya** [llfbandit/dio_cache_interceptor#20]
I am using dio_cache_interceptor: ^2.3.1 with dio: ^4.0.0.

I download the ReadMe example and Run it on my system.

After trying multiple times my response is not cached.

Here is ss. 

![Simulator Screen Shot - iPhone 11 Pro - 2021-05-11 at 19 29 22](https://user-images.githubusercontent.com/11865669/117828236-45707f00-b28f-11eb-90ad-9fcdb33171bf.png)

And here without the internet.
 
![Simulator Screen Shot - iPhone 11 Pro - 2021-05-11 at 19 29 34](https://user-images.githubusercontent.com/11865669/117828788-c760a800-b28f-11eb-9151-e67c0cb691e9.png)

Here it supposes to return my cache response.

Let me know If I am missing something.

**Comment by llfbandit** [comment]
HTTP cache does not mean offline cache. If you want to achieve such a behaviour, you should provide `hitCacheOnErrorExcept` attribute.
Also, guessing from your description, you should only use request policy. refresh is to override previously cached value.

**Comment by jigarfumakiya** [comment]
Thanks for the reply.
I have hitCacheOnErrorExcept attribute and still is not working and Yes I have tried only request policy.

Here

f```
inal options = CacheOptions(
      // A default store is required for interceptor.
      store: cacheOptions,
      // Default.
      policy: CachePolicy.request,
      // Optional. Returns a cached response on error but for statuses 401 & 403.
      hitCacheOnErrorExcept: [401, 403,404],
      // Optional. Overrides any HTTP directive to delete entry past this duration.
      maxStale: const Duration(days: 7),
      // Default. Allows 3 cache sets and ease cleanup.
      priority: CachePriority.normal,
      // Default. Body and headers encryption with your own algorithm.
      cipher: null,
      // Default. Key builder to retrieve requests.
      keyBuilder: CacheOptions.defaultCacheKeyBuilder,
      // Default. Allows to cache POST requests.
      // Overriding [keyBuilder] is strongly recommended.
      allowPostMethod: true,

    );
```

**Comment by iampato** [comment]
Also not working on my end:

My app already use hive for either services:
```
  CacheOptions options = CacheOptions(
    // A default store is required for interceptor.
    store: HiveCacheStore(null),
    // Default.
    policy: CachePolicy.refresh,
    // Optional. Returns a cached response on error but for statuses 401 & 403.
    hitCacheOnErrorExcept: [401, 403],
    // Optional. Overrides any HTTP directive to delete entry past this duration.
    maxStale: const Duration(days: 7),
    // Default. Allows 3 cache sets and ease cleanup.
    priority: CachePriority.normal,
    // Default. Body and headers encryption with your own algorithm.
    cipher: null,
    // Default. Key builder to retrieve requests.
    keyBuilder: CacheOptions.defaultCacheKeyBuilder,
    // Default. Allows to cache POST requests.
    // Overriding [keyBuilder] is strongly recommended.
    allowPostMethod: false,
  );

```

Version used ` dio_cache_interceptor: ^2.3.1`

**Comment by fahjan** [comment]
please, i need my app to work without internet.
i need this feature to solve.

**Comment by bdremynoel** [comment]
Guys I can't reproduce it. Just modified the example provided like this:

```dart
pp.getApplicationDocumentsDirectory().then((dir) {
      cacheStore = DbCacheStore(databasePath: dir.path, logStatements: true);
      // cacheStore = FileCacheStore(dir.path);

      dio = Dio()
        ..interceptors.add(
          DioCacheInterceptor(
              options:
                  CacheOptions(store: cacheStore, hitCacheOnErrorExcept: [])),
        );
    });
```

And I get my reponse even if I'm offline.
I'll update the example to demonstrate it...

**Comment by bdremynoel** [comment]
Done.
https://github.com/llfbandit/dio_cache_interceptor/blob/master/example/lib/main.dart

**Comment by iampato** [comment]
Example with hive ??

**Comment by llfbandit** [comment]
- add hive to the example pubspec.yaml
- cacheStore = HiveCacheStore(dir.path)
- You're good to go
