### ISSUE TITLE
file_cache_store.dart is not exported

### ISSUE THREAD

**Issue by vanlooverenkoen** [llfbandit/dio_cache_interceptor#23]
file_cache_store.dart is not exported so we have to manually import the file_cache_store file.

`import 'package:dio_cache_interceptor/src/store/file_cache_store.dart'`

the file_cache_store.dart should be exported as well

**Comment by bdremynoel** [comment]
No?

https://github.com/llfbandit/dio_cache_interceptor/blob/a8521eeb6bfb710bd513c1a97228f797c8f8fa5c/lib/dio_cache_interceptor.dart#L4

**Comment by vanlooverenkoen** [comment]
Hmm strange. I had to manually import that file. I will double check tomorrow

**Comment by vanlooverenkoen** [comment]
It is not compiling for me:


![image](https://user-images.githubusercontent.com/21172855/122269075-16c47480-cedd-11eb-9dfc-c783d92ad7a6.png)

After adding this import
```
import 'package:dio_cache_interceptor/src/store/file_cache_store.dart';
```

it does compile:
![image](https://user-images.githubusercontent.com/21172855/122269166-33f94300-cedd-11eb-80a2-1fee269d3e1a.png)

**Comment by vanlooverenkoen** [comment]
@bdremynoel I am still having the same issue with version 3.0.0

**Comment by vanlooverenkoen** [comment]
Right now I have to import 
```
import 'package:dio_cache_interceptor/src/store/file_cache_store/file_cache_store_io.dart';
```

Otherwise FileCachStore is not found. And I can not compile

**Comment by llfbandit** [comment]
Should be finally good in 3.0.1
