### ISSUE TITLE
Is it possible to move dbcache to a single pakcages

### ISSUE THREAD

**Issue by jiechic** [llfbandit/dio_cache_interceptor#26]
Is it possible to move dbcache to a single pakcages
I hope that dio_cache_interceptor does not rely on the database. After all, database dependency is a huge feature, and a large amount of code will be introduced to the native end, which makes it unfriendly for us who use flutter module instead of flutter application

**Comment by llfbandit** [comment]
Done in 3.0.0

**Comment by jiechic** [comment]
thanks
