### ISSUE TITLE
import Error while using dio_cache_interceptor_db_store  

### ISSUE THREAD

**Issue by pravindia** [llfbandit/dio_cache_interceptor#27]
It seems you removed db_cache_store from dio_cache_interceptor and not from dio_cache_interceptor_db_store package

Error Log:

Error: Error when reading '../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cache_interceptor-3.0.0/lib/src/store/db_cache_store/database.dart': No such file or directory

import 'package:dio_cache_interceptor/src/store/db_cache_store/database.dart';
       ^

../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cache_interceptor_db_store-3.0.0/lib/src/store/dio_cache_interceptor_db_store.dart:35:14: Error: Method not found: 'openDb'.
  final DioCacheDatabase _db;
        ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cache_interceptor_db_store-3.0.0/lib/src/store/dio_cache_interceptor_db_store.dart:29:9: Error: 'DioCacheDatabase' isn't a type.
  final DioCacheDatabase _db;
        ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cache_interceptor_db_store-3.0.0/lib/src/store/dio_cache_interceptor_db_store.dart:29:9: Error: Type 'DioCacheDatabase' not found.

       ^

**Comment by llfbandit** [comment]
Thanks for the report.
Cleaned up the project. Should be good in v3.0.1
