### ISSUE TITLE
Flutter/ Analysis issue: The function 'FileCacheStore' isn't defined

### ISSUE THREAD

**Issue by miduch** [llfbandit/dio_cache_interceptor#29]
I keep getting analysis issue: The function 'FileCacheStore' isn't defined in Android Studio. It can compile but this error is really annoying/ shown all the time in IDE. 

Also when running  "dart migrate" i get this error and migration fails. 

Analyzing project...
[---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/]
1 analysis issue found:
  error • The function 'FileCacheStore' isn't defined at lib/services/service_locator.dart:27:48 • (undefined_function)

**Comment by llfbandit** [comment]
Should be finally good in 3.0.1.

**Comment by llfbandit** [comment]
@miduch does it mean it's ok to close the issue?

**Comment by miduch** [comment]
I guess so
