### ISSUE TITLE
Cannot open file. 

### ISSUE THREAD

**Issue by vanlooverenkoen** [llfbandit/dio_cache_interceptor#30]
My Implementation
```
  Future<DioCacheInterceptor> provideDioCacheInterceptor() async {
    final appDocDir = await getApplicationDocumentsDirectory();
    final options = CacheOptions(
      store: FileCacheStore('${appDocDir.path}/cache'),
      policy: CachePolicy.request,
      maxStale: const Duration(days: 90),
      priority: CachePriority.normal,
      keyBuilder: CacheOptions.defaultCacheKeyBuilder,
      allowPostMethod: false,
    );
    return DioCacheInterceptor(options: options);
  }
```

The exception
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FileSystemException: Cannot open file, path = '/data/user/0/package-name/app_flutter/cache/normal/f9c8f07d-eeba-5bfa-aacd-eaa76ba03fa8' (OS Error: No such file or directory, errno = 2). Error thrown null.
       at _File.readAsBytesSync(_File.java)
       at FileCacheStore._deserializeContent(FileCacheStore.java:136)
       at FileCacheStore.get(FileCacheStore.java:61)
       at DioCacheInterceptor._getCacheResponse(DioCacheInterceptor.java:270)
       at DioCacheInterceptor._getResponse(DioCacheInterceptor.java:284)
       at DioCacheInterceptor.onError(DioCacheInterceptor.java:125)
       at DioMixin.fetch._errorInterceptorWrapper.<fn>.<fn>.<fn>(<fn>.java:557)
       at DioMixin.checkIfNeedEnqueue(DioMixin.java:795)
       at DioMixin.fetch._errorInterceptorWrapper.<fn>.<fn>(<fn>.java:555)
       at _CustomZone.bindCallback.<fn>(bindCallback.java)
       at safeRun.<fn>(safeRun.java:7)
```

I get this error in firebase. But I can not reproduce it.
Device:
- Oppo A9 2020

**Comment by llfbandit** [comment]
Does `provideDioCacheInterceptor` can be called multiple times in your app?
Do you use `FileCacheStore` to directly elsewhere?

I guess #31 is pretty similar to this one, it should never happen unless you have environmental "noise" related to my questions or other things I can't guess out.

**Comment by vanlooverenkoen** [comment]
No it it setup as a singleton. So it is only called once. The FileCacheStore is only be used once

**Comment by llfbandit** [comment]
`_deserializeContent` is only called if the file exists. The file is read just after the finding.
It's nearly impossible to not be able to process it.

Are you sure to not play with the folder `getApplicationDocumentsDirectory`?

**Comment by vanlooverenkoen** [comment]
`getApplicationDocumentsDirectory` is also used for our database. 

- /applicationdocumentsdirectory/cache/* -> dio_cach_interceptor folder
- /applicationdocumentsdirectory/db.sqlite -> db file

Because the dio_cache_interceptor has its own folder I would expect it is isolated from the other files

**Comment by llfbandit** [comment]
Yes it is but I cannot guarantee that you do same on your side. Unless you can provide more info I won't be capable of doing anything on this. Thanks for your comprehension.

**Comment by vanlooverenkoen** [comment]
That folder is never touched on our side. It is only used by dio_cache_interceptor. What type of extra information do you need in order to better pinpoint where this problem is happening?

**Comment by llfbandit** [comment]
File concurrent access is now fixed. File cache store is now external.
https://pub.dev/packages/dio_cache_interceptor_file_store

**Comment by vanlooverenkoen** [comment]
We just updated to the latest version. We are using obfuscation now in our app. Because 90% of our non fatal crashes were caused by dio_cache_interceptor we will probably see if the error goes crash rate goes down or not. We will keep you posted
