### ISSUE TITLE
'GeneratedTextColumn'  Not found

### ISSUE THREAD

**Issue by ericel** [llfbandit/dio_cache_interceptor#32]
I am sure why exactly but this is the error I get trying to run this plugin:
  

>  - 'DioCache' is from 'package:dio_cache_interceptor_db_store/src/store/database.dart' ('../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/dio_cache_interceptor_db_store-3.0.1/lib/src/store/database.dart').
>     Try correcting the name to the name of an existing method, or defining a method named 'GeneratedTextColumn'.
>         return GeneratedTextColumn('url', $tableName, false,
>                ^^^^^^^^^^^^^^^^^^^
>     Command PhaseScriptExecution failed with a nonzero exit code

**Comment by yyyy-ltd** [comment]
you solved it?

**Comment by llfbandit** [comment]
Did you upgrade Moor to ^4.4.0 ?

It seems that the generated database file is not compatible with previous versions.

Can you try with Moor version 4.3 ?

**Comment by ericel** [comment]
Nope! I didn't install more independently. I will delete the old database and test and see if that may be the problem.

**Comment by llfbandit** [comment]
Thanks!

In any case, I'm updating dependencies and regenerate new `database` file with Moor 4.4.1.

**Comment by llfbandit** [comment]
Should be fixed in 3.0.2

**Comment by ericel** [comment]
Thanks a lot!. I will try that now.
