### ISSUE TITLE
Connect timeout will return expire cache data

### ISSUE THREAD

**Issue by wangiv2** [llfbandit/dio_cache_interceptor#33]
Hi,

I encounter the issue that it will return the expire cache data when the http request connect timeout, it intercepted the connect timeout exception handling logic. Can you consider adding the connect timeout case to the options.hitCacheOnErrorExcept? Let us decide whether we want to return data in connect timeout case. many thanks.

![image](https://user-images.githubusercontent.com/7232767/125581154-9930ff09-dff8-407b-8c86-272b63df7d0c.png)

**Comment by llfbandit** [comment]
`hitCacheOnErrorExcept` was designed to trap any network error. In fact, connect TO, read/write TO, general network failure and so on are pointing to the same issue. The client did not connect to the origin server. And from the user point of view, the detailed error has no meaning for him. 

As a note, regarding this option or not, the cache value read is not expired.

Finally, to answer to the issue, you can directly call your store to handle specific cases. I really don't know why you would separate connect TO from let's say read TO. Need additional info here.
