### ISSUE TITLE
Issue with post calls with different bodies

### ISSUE THREAD

**Issue by arbile26** [llfbandit/dio_cache_interceptor#37]
When I do `dio.post` with the same url but with different body, the interceptor caches the first call and returns the same cached response for all other post call although each one of them has a different body.

**Comment by llfbandit** [comment]
Hi,

This is expected. If you need to cache data with POST method you need to override `keyBuilder` to include key generation with the body. By default, `keyBuilder` generates keys with the given url only.

**Comment by arbile26** [comment]
> Hi,
> 
> This is expected. If you need to cache data with POST method you need to override `keyBuilder` to include key generation with the body. By default, `keyBuilder` generates keys with the given url only.

Thanks.
I know it's a stupid question, but honestly, I didn't know how to override the `keyBuilder`. It's not explained in the decumentation.

**Comment by k00na** [comment]
I'm struggling while trying to find out how to over-ride keyBuilder in order to be able to cache POST requests. Is there a good example of an overridden keyBuilder that you can share? Would be very much appreciated 🙏

**Comment by arbile26** [comment]
> I'm struggling while trying to find out how to over-ride keyBuilder in order to be able to cache POST requests. Is there a good example of an overridden keyBuilder that you can share? Would be very much appreciated 🙏

I did it by overriding the keyBuilder like that:
`keyBuilder: (request) => myID,`
`myID` is the key that will be linked to the request.
