### ISSUE TITLE
onError is throwing an exception when the response is expired, cached and encrypted

### ISSUE THREAD

**Issue by greg-tekai-com** [llfbandit/dio_cache_interceptor#38]
We're running into an interesting scenario.  We're using a CacheCipher to encrypt/decrypt our json responses.  We've hit a scenario where a call will hit the onError function within the dio_cache_interceptor, where we have an expired cached response and returnResponse flag is determined to be true (304).  Then, at the end of the call to `_getResponse(...)`, it's trying to deserialize the content from an encrypted cached response without decrypting the body or headers, just after updating the cache store, in `updatedCache.toResponse(request, fromNetwork: true)`.  As we're using json, it's trying to convert utf into a string, but as it's still encrypted, it throws a format exception.

```
Error: FormatException: Missing extension byte (at offset 2) Utf8Codec.decode dart:convert
$.deserializeContent content_serialization.dart:31
CacheResponse.toResponse cache_response.dart:70
DioCacheInterceptor._getResponse dio_cache_interceptor.dart:301
DioCacheInterceptor.onError dio_cache_interceptor.dart:125
```

We were also using a cache policy of request, hence the expired requirement, but suspect it should also fail for any of the refresh policies / scenarios that has a cached response but can call onError.

Version 3.0.1 / Dio 4.0.0

Otherwise, it's been fairly robust for what we've done so far.  Nice work.

**Comment by llfbandit** [comment]
Thanks for the report!

If I understand well, the issue is when we're trying to wrap the `CacheResponse` to `Response` via `updatedCache.toResponse(request, fromNetwork: true)` (line 301).

Because the content is crypted (again) at this time, bytes cannot be converted. Is that it?

**Comment by greg-tekai-com** [comment]
Thanks for the quick fix!  I'll try out the new release, but looks like it should work.
