### ISSUE TITLE
Documentation needs to be a bit more clear about http directives.

### ISSUE THREAD

**Issue by NamanShergill** [llfbandit/dio_cache_interceptor#4]
For example, what does the package do if there is an etag directive to a call? Does it check with the API first when the cache is enabled, for the etag, or gives data from the cache directly, when the CachePolicy is set to CachePolicy.request, or only for CachePolicy.refresh?

**Comment by NamanShergill** [comment]
If someone could clear up the behavior for me a bit I could help in updating the docs!

**Comment by llfbandit** [comment]
You mean if you set cache header checks by yourself?
This is ignored. Requests are always checked with `CacheKeyBuilder`.

You don't have to mess with those things, just request and let this package do its job.
It tries to respect standards (at least with the current sub-set).

So for your example:
- 1st call with etag (and cache-control) in response => cache
- 2nd call, cache will be called and checked to ensure there's no expiry. If expired, network request will be made with corresponding headers expecting 200 (or still possible 304). If cache is still fresh, cache value will be returned directly.

**Comment by llfbandit** [comment]
Oh sorry, I was writing this for version 2. Version 1 is unsupported now.
In both versions, refresh skips cache. In version 2, there's no more requestFirst / cacheFirst, only request which does what I wrote before.

**Comment by NamanShergill** [comment]
> Oh sorry, I was writing this for version 2. Version 1 is unsupported now.
> In both versions, refresh skips cache. In version 2, there's no more requestFirst / cacheFirst, only request which does what I wrote before.

Got it, thank you!

**Comment by NamanShergill** [comment]
Okay, so I updated the package to 2.0.0-beta.7, yet it doesn't seem like the Etags are being sent in the outgoing request even if the policy is set to refresh, and there is no 304 response, just seems like it downloads all the data again. I am setting it up as mentioned in the readme, is there anything extra I need to do?

**Comment by NamanShergill** [comment]
Nevermind, I was using MemCacheStore which did not let me do this. It's working now.

**Comment by alguintu** [comment]
@NamanShergill can you share a snippet of code how you made the request with the etag? I can't seem to make it work to check back with server to check if there are changes first before deferring to the cache. I'm not even sure if I understand the flow correctly. My understanding is that if the cache is fresh but the etag is different from the server, it should show the fresh results instead of the cached items. Any help is appreciated. Thanks.

**Comment by NamanShergill** [comment]
> @NamanShergill can you share a snippet of code how you made the request with the etag? I can't seem to make it work to check back with server to check if there are changes first before deferring to the cache. I'm not even sure if I understand the flow correctly. My understanding is that if the cache is fresh but the etag is different from the server, it should show the fresh results instead of the cached items. Any help is appreciated. Thanks.

Hey, so the expected flow is

Items is cached -> Cache is shown without requesting the server if it is "fresh", ie, the max age isn't over, and if it is "stale", it'll request the server with the required ETag headers. If the server gives a 304 error, it'll then use the cache and refresh the max age value in it.
