### ISSUE TITLE
Issues with `Expires` header

### ISSUE THREAD

**Issue by Ben-Baert** [llfbandit/dio_cache_interceptor#40]
Hi,

Maybe I'm missing something obvious, but in the `isExpired` check, if the `Expires` header is set, you compare `checkedDate` with `checkedExpires`, both of which are constant, unchanging values I believe. This would imply that that this check is always `false` (assuming the `Expires` value is in the future at the time of the request). 

Shouldn't it be  `checkedExpires.difference(DateTime.now()).isNegative;` on L120? (see https://github.com/llfbandit/dio_cache_interceptor/blob/21930fe042eb4143aecb5efbde4c0df7bc1ed432/dio_cache_interceptor/lib/src/model/cache_response.dart#L120)

```dart
bool isExpired() {
    final cControl = cacheControl;
    final checkedDate = date ?? responseDate;

    if (cControl != null) {
      if (cControl.noCache ?? false) {
        return true;
      }

      final checkedMaxAge = cControl.maxAge;
      if (checkedMaxAge != null && checkedMaxAge > 0) {
        final maxDate = checkedDate.add(Duration(seconds: checkedMaxAge));
        return maxDate.isBefore(DateTime.now());
      }
    }

    final checkedExpires = expires;
    if (checkedExpires != null) {
      return checkedExpires.difference(DateTime.now()).isNegative;
    }

    return true;
  }
}
```

Second question (separate but related): 

In the `_shouldStoreResponse` method, shouldn't there be a check if the `exiresHeader != null`, i.e. `result |= response.headers[expiresHeader] != null;` around L158? (https://github.com/llfbandit/dio_cache_interceptor/blob/38313412ba297d339f8e47b3710f342f4cc27fc6/dio_cache_interceptor/lib/src/dio_cache_interceptor.dart#L158) 

```dart
  bool _shouldStoreResponse(Response response, {CachePolicy? policy}) {
    if (policy == CachePolicy.forceCache ||
        policy == CachePolicy.refreshForceCache) {
      return true;
    }

    var result = response.headers[etagHeader] != null;
    result |= response.headers[lastModifiedHeader] != null;
    result |= response.headers[expiresHeader] != null

    final cacheControl = CacheControl.fromHeader(
      response.headers[cacheControlHeader],
    );

    if (cacheControl != null) {
      final checkedMaxAge = cacheControl.maxAge;
      result |= checkedMaxAge != null && checkedMaxAge > 0;
      result &= !(cacheControl.noStore ?? false);
    }

    return result;
  }
```

I made these changes for testing purposes on a fork after I had issues with the `Expires` header and it seems to be working correctly with the two changes above. But again, maybe I've just missed something obvious somewhere.

Thank you for your time and the great package!

Ben

**Comment by llfbandit** [comment]
Sorry for the late reply. 
`Expires` field (if any) should be refreshed on each response from origin server on status 304. 
If I remember well, dio interceptor traps this status with `onError` callback.
