### ISSUE TITLE
Update ObjectBox cache store to latest models

### ISSUE THREAD

**Issue by llfbandit** [llfbandit/dio_cache_interceptor#47]
@cmengler Are you able to write this migration?

- Add `requestDate` on `CacheResponse`
- Add missing fields on `CacheControl` (min-fresh, max-stale, must-revalidate)

**Comment by cmengler** [comment]
Definitely @llfbandit 👍  I'll have a PR open in the next day or two when I return back from break :)

**Comment by llfbandit** [comment]
Thanks for being around.

Other stores are pretty much ready if that can help you and changelog is also written.
Well I'm not very far either ;).

I forgot to mention to setup `requestDate` to 150 millis in the past against `responseDate` for existing/older data.
I still need to add another test for stores too to ensure that `CacheControl` is well filled when reading data.

**Comment by cmengler** [comment]
Apologies for the delay @llfbandit -- I've got my changes pushed to a branch now, I'll do a manual test first before I open up a PR soon :)

**Comment by llfbandit** [comment]
v1.0.0 is now published! Thanks for your time @cmengler. 👍
