### ISSUE TITLE
[BUG] Cache is not updated with the new response date if 304 response is received. It always checks with the first ever response date to know if data in cache is expired.

### ISSUE THREAD

**Issue by NamanShergill** [llfbandit/dio_cache_interceptor#5]
The 304 response also has headers for cache control, shouldn't the cached data be updated with those?

**Comment by NamanShergill** [comment]
https://github.com/llfbandit/dio_cache_interceptor/blob/c0c923c3c7cdb182a2f9044bf53d789b32a96115/lib/src/dio_cache_interceptor.dart#L116

It just fetches the cached data here but does not update it with the new date that is being used  here:
https://github.com/llfbandit/dio_cache_interceptor/blob/c0c923c3c7cdb182a2f9044bf53d789b32a96115/lib/src/model/cache_response.dart#L102

Causing it to always say it is expired.

**Comment by llfbandit** [comment]
This will be available in next version.

**Comment by llfbandit** [comment]
Fixed in aadd378b.
Still need to add test on it.

**Comment by llfbandit** [comment]
Fixed in rc1
