### ISSUE TITLE
Add option to cache to isar

### ISSUE THREAD

**Issue by yringler** [llfbandit/dio_cache_interceptor#50]
Add isar cache response handler?

Disclaimer: this is probably pointless - there are already a bunch of caching options, and whatever their speed they're more than fast enough.
But [isar](https://pub.dev/packages/isar) just went stable, and it's really cool, and it has to be added to this project.
From the maker of hivedb (@leisim), a super fast nosql (unlike hive, doesn't have to load everything to memory), built on a safe rust wrapper for a fast C libmdbx

This is something which doesn't seem difficult to implement, and I have plenty of experience with hivedb and drift, so maybe something I would open a PR for, maybe after I've used isar at least a little bit in my app.

**Comment by llfbandit** [comment]
Thanks for the proposal.
If you ensure to be a maintainer for this package I'd be glad to add it to the collection.

**Comment by yringler** [comment]
Very tempting. We'll see what happens.
