### ISSUE TITLE
No file in cache folder

### ISSUE THREAD

**Issue by NassB** [llfbandit/dio_cache_interceptor#54]
I am trying to use dio_cache_interceptor_file_store with FileCacheStore to store data into cache for each GET request.
I am using DIO with retrofit, so I imagine that both are compatible with dio_cache_interceptor.

I dont want to depends on http directives, so I am using CachePolicy.forceCache.

```
@RestApi(baseUrl: ApiRoutes.baseUrl)
abstract class ApiClient {

  factory ApiClient(Dio dio) {
    dio.options = BaseOptions(
      sendTimeout: 20000,
      connectTimeout: 20000,
      receiveTimeout: 20000,
      contentType: 'application/json',
    );

    pp.getTemporaryDirectory().then((dir) {
      CacheOptions _cacheOptions = CacheOptions(
        store: FileCacheStore(dir.path),
        policy: CachePolicy.forceCache,
        maxStale: const Duration(minutes: 50),
      );

      dio.interceptors.add(DioCacheInterceptor(options: _cacheOptions));
    });

    return _ApiClient(dio);
  }

  @GET(ApiRoutes.foo + '/{id}/bar')
  Future<List<FooBar>> getFooBar(
    @Path() String foo, {
    @Header('Range') String? bar = '',
  });
}
```

And then calling getFooBar from my repository
 
```
class FooBarRepository {
  late Dio _dio;
  late ApiClient _userClient;

  FooBarRepository() {
    _dio = Dio();
    _userClient = ApiClient(_dio);
  }

  Future<List<FooBar>?> getFooBar({
    String? id = '00000000-0000-0000-0000-000000000000',
  }) async {
    List<FooBar> response;
    try {
      response = await _userClient.getFooBar(id!);
    } on DioError catch (error) {
      return Future.value(null);
    }

    return response;
  }
}
```

My device is rooted so when I receive the data from the server I am able to see if the cache folder is empty or not, and unfortunately it is always empty.
Status code 200 -> I receive the data without problem
Status code 403 -> Nothing is loaded from the cache

But this is not working like I expected, so I dont know if I am missing something from the documentation.

**Comment by llfbandit** [comment]
I guess it would work too.
Can you check in your repositories that your wrapped dio instance has the interceptor?

Also, I assume that 403 status code is a typo.
With forceCache you will never get 304 status code.

**Comment by NassB** [comment]
I fixed some part of my code, so the result of my request is in the cache now.
The problem was coming from `getTemporaryDirectory()`, because the function was called in the factory constructor, and because I didn't set `hitCacheOnErrorExcept` parameter to [].
So it's all working now !

The rest API is only accessible through a VPN, so all request are not working when I am not connected to the VPN, this is why I was talking about that 403 status code to test if the data in the cache will be used when I am not connected.
The application will never receive a 304 status code at the moment (maybe in the future).

So now when I am testing the app : 
Status code 200 -> I receive the data without problem and the data is in the cache
Status code 403 -> Data is loaded from the cache like I want

Thanks you for your work on this lib !
