### ISSUE TITLE
add update to CacheStore class

### ISSUE THREAD

**Issue by hasanm08** [llfbandit/dio_cache_interceptor#55]
maybe this code be usefull

> better to add ```copyWith()``` for CacheResponse

```dart
Future<void> update(key, content) async {
    final res= await get(key);
    if (res != null) {
      await delete(res.key);
      final CacheResponse response = CacheResponse(
          cacheControl: res.cacheControl,
          content: utf8.encode(jsonEncode(content)),
          date: DateTime.now(),
          eTag: res.eTag,
          expires: DateTime.now().add(const Duration(seconds: 45)),
          headers: res.headers,
          lastModified: DateTime.now(),
          key: res.key,
          maxStale: res.maxStale,
          priority: res.priority,
          requestDate: res.requestDate,
          responseDate: res.requestDate,
          url: res.url);
      await set(response);
    }
  }
  ```

**Comment by llfbandit** [comment]
Thanks but I don't think this is needed.
Have you a use case in mind? Feel free to re-open.

**Comment by hasanm08** [comment]
In some cases like bookmarking the cached data will effect the result and for every action like that cache will be updated

**Comment by hasanm08** [comment]
@llfbandit can you check please?

**Comment by llfbandit** [comment]
This will not be implemented because it would imply to provide all other parameters to update the cached response properly for every others.
Your use case is really business specific (and unrelated to HTTP generic cache) so, there's no QoL of adding this.

**Comment by llfbandit** [comment]
I've read again your issue.
In fact, what you want is a `copyWith` method for `CachedResponse` not an `update` method on `CacheStore` ?
