### ISSUE TITLE
MemCacheStore response size computation

### ISSUE THREAD

**Issue by eric-taix** [llfbandit/dio_cache_interceptor#56]
Hi,

I had an issue with `MemCacheStore` and I had a look to the source code to understand what was wrong:

My response has a content size of 95,88KB but it was skipped from being put into the cache because it's too heavy. When I look to the `_LruMap` the content size of the response if multiply by 8! Is it for bytes conversion or a magic number?
 (https://github.com/llfbandit/dio_cache_interceptor/blob/master/dio_cache_interceptor/lib/src/store/mem_cache_store.dart#L164) which exceeds the default `maxEntrySize` (and that's why the response is skipped from being put into the cache). I'm wondering why the content size is multiply by 8? Is it a bug or did I miss something as I would personally just use the content size + the header size which is already a bytes length, to compute the response overall size?

I know that I can set a new `maxEntrySize` (and I'll change it as a workaround) but the default value seems enough for my requirements.

Suggestion: It's not easy to understand that the response has oversized the maximum entry size and it takes times. Perhaps a log could be a good option to help developers to understand that the response could not have be stored in the cache due to an oversized content size?

dio_cache_interceptor version `3.2.2`

**Comment by llfbandit** [comment]
Thanks for the report!
I'm away from a computer for the next 2 weeks but it seems you're right.

**Comment by eric-taix** [comment]
No problem, enjoy your holidays ;-) 
I've already applied a new `maxEntrySize` as a workaround and thanks for your quick reply.

**Comment by llfbandit** [comment]
This is now fixed on master branch.

Feedback welcomed.

**Comment by llfbandit** [comment]
Released in v3.2.3
