### ISSUE TITLE
Feature Request: An option to specify a maxAge that would override the maxAge from the response headers.

### ISSUE THREAD

**Issue by NamanShergill** [llfbandit/dio_cache_interceptor#6]

**Comment by llfbandit** [comment]
I won't do that. If server sends this data, there's no reason to not trust it.
Workarounds are `CacheOptions.maxStale` or `CachePolicy.cacheForce`.

**Comment by NamanShergill** [comment]
> 
> 
> I won't do that. If server sends this data, there's no reason to not trust it.
> Workarounds are `CacheOptions.maxStale` or `CachePolicy.cacheForce`.

I see, but would it not be better to let the application have an option if it would prefer to show the cached version for 5 minutes instead of if the server says, 60 seconds? Just from a bandwidth saving POV.

**Comment by NamanShergill** [comment]
> Workarounds are CacheOptions.maxStale or CachePolicy.cacheForce.

But using these it won't be possible to achieve behavior like, getting the data from the cache first for x amount of time, followed  by trying to refresh after that and using the cached version only if there was an error (like no connectivity), would it?

Would just limit the leeway an application has if it is stuck with only being able to do one of these two things.

**Comment by llfbandit** [comment]
I agree, but this is still the responsability of server team, not client.

To achieve this behaviour, you could access to the store and make checks by yourself.
Here's a foo example, for inspiration, to wrap your calls:
```dart
RequestOptions request = RequestOptions(...);
final key = cacheOptions.defaultCacheKeyBuilder(request);

final cache = await store.get(key);
if (cache != null && DateTime.now().difference(cache.responseDate).inMinutes < 5) {
  return cache.toReponse(request, fromNetwork: false);
} else {
  // request as you normally would
}
```

**Comment by NamanShergill** [comment]
> I agree, but this is still the responsability of server team, not client.
> 
> To achieve this behaviour, you could access to the store and make checks by yourself.
> Here's a foo example, for inspiration, to wrap your calls:
> 
> ```dart
> RequestOptions request = RequestOptions(...);
> final key = cacheOptions.defaultCacheKeyBuilder(request);
> 
> final cache = await store.get(key);
> if (cache != null && DateTime.now().difference(cache.responseDate).inMinutes < 5) {
>   return cache.toReponse(request, fromNetwork: false);
> } else {
>   // request as you normally would
> }
> ```

Thank you, I'll do this!
(In some cases one could be working with a public API, not giving them an option to get the server team to modify the cache control headers which is why I brought it up, but looks like this will get the job done, atleast in my use case!)

**Comment by wer-mathurin** [comment]
@llfbandit 
This is exactly the use case described by @NamanShergill  that we are facing,(using a public API that do not manage caching on the server side) and because we currently use retrofit for not coding the request but ourselves, we can't can use your elegant solution :-(

**Comment by llfbandit** [comment]
The previous proposals are the way to go for this kind of behaviour.
Managing the cache on the client side equals to an infinite list of specific needs. To keep this package clean and understandable I can't agree to implement those requests.
Also, adding an interceptor is not a problem since the code would be the same, there's no performance pitfall here.

**Comment by NamanShergill** [comment]
@llfbandit You're right. I had not considered the possibility of adding an interceptor when I had made this issue. I concur that that is the best approach.

**Comment by clragon** [comment]
I understand.

However, this seems extremely impratical.
Lets say I want to insert an Interceptor before `DioCacheInterceptor`, 
that will simply set the `maxAge` value to something I desire.

If I want to configure this per request, I have to include my replacement value inside of the extras for the Options I pass to the request. Currently, the options are

```dart
options: _defaultCacheOptions
    .copyWith(maxStale: const Nullable(Duration(minutes: 5)))
    .toOptions(),
``` 

which will take up my entire options Parameter for Dio.
Whatever comes next seems to result in an ugly mess or alot of boilerplate.

CacheOptions does not expose the key it uses to be placed in the extras, so if I wanted to add my own extra value beside it, I would have to obtain the CacheOptions Map with toExtra, then add my value, and then pass it to a new Options object.

CacheOptions also has no way of passing other extras through it.

If I wanted to add the `maxAge` value as a part of `CacheOptions`, I would have to extend it, copy all of its default values into a new constructor and pass them to super and then also override and adjust its copyWith method.

I have in fact done that, and implemented an extension plus a new interceptor so I can override the maxAge for each request:

<details>
<summary>CacheConfig extends CacheOptions</summary>

```dart
class CacheConfig extends CacheOptions {
  final Duration? maxAge;

  CacheConfig({
    CachePolicy policy = CachePolicy.request,
    List<int>? hitCacheOnErrorExcept,
    CacheKeyBuilder keyBuilder = CacheOptions.defaultCacheKeyBuilder,
    Duration? maxStale,
    this.maxAge,
    CachePriority priority = CachePriority.normal,
    CacheStore? store,
    CacheCipher? cipher,
    bool allowPostMethod = false,
  }) : super(
          policy: policy,
          hitCacheOnErrorExcept: hitCacheOnErrorExcept,
          keyBuilder: keyBuilder,
          maxStale: maxStale,
          priority: priority,
          store: store,
          cipher: cipher,
          allowPostMethod: allowPostMethod,
        );

  static CacheConfig? fromExtra(RequestOptions request) {
    final CacheOptions? config = CacheOptions.fromExtra(request);
    if (config != null && config is CacheConfig) {
      return config;
    }
    return null;
  }

  @override
  CacheConfig copyWith({
    CachePolicy? policy,
    Nullable<List<int>>? hitCacheOnErrorExcept,
    CacheKeyBuilder? keyBuilder,
    Nullable<Duration>? maxStale,
    Nullable<Duration>? maxAge,
    CachePriority? priority,
    CacheStore? store,
    Nullable<CacheCipher>? cipher,
    bool? allowPostMethod,
  }) =>
      CacheConfig(
        policy: policy ?? this.policy,
        hitCacheOnErrorExcept: hitCacheOnErrorExcept != null
            ? hitCacheOnErrorExcept.value
            : this.hitCacheOnErrorExcept,
        keyBuilder: keyBuilder ?? this.keyBuilder,
        maxStale: maxStale != null ? maxStale.value : this.maxStale,
        maxAge: maxAge != null ? maxAge.value : this.maxAge,
        priority: priority ?? this.priority,
        store: store ?? this.store,
        cipher: cipher != null ? cipher.value : this.cipher,
        allowPostMethod: allowPostMethod ?? this.allowPostMethod,
      );
}
```
</details>

<details>
<summary>CacheMaxAgeInterceptor</summary>

```dart
class CacheMaxAgeInterceptor extends Interceptor {
  static const _cacheControlHeader = 'cache-control';

  final CacheConfig _options;

  CacheMaxAgeInterceptor({required CacheConfig options}) : _options = options;

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    final CacheConfig config =
        CacheConfig.fromExtra(response.requestOptions) ?? _options;

    final CacheControl cacheControl = CacheControl.fromHeader(
      response.headers[_cacheControlHeader],
    );

    final int updatedMaxAge =
        config.maxAge?.inMilliseconds ?? cacheControl.maxAge;

    final CacheControl updatedCacheControl = CacheControl(
      maxAge: updatedMaxAge,
      privacy: cacheControl.privacy,
      maxStale: cacheControl.maxStale,
      minFresh: cacheControl.minFresh,
      mustRevalidate: cacheControl.mustRevalidate,
      noCache: cacheControl.noCache,
      noStore: cacheControl.noStore,
      other: cacheControl.other,
    );

    response.headers.set(_cacheControlHeader, updatedCacheControl.toHeader());

    super.onResponse(response, handler);
  }
}
```
</details>

and this works really well, when used like this:

```dart
_defaultCacheOptions = CacheConfig(
  maxAge: const Duration(minutes: 5),
  store: await _cacheStore,
);
dio.interceptors.addAll([
  CacheMaxAgeInterceptor(options: _defaultCacheOptions),
  DioCacheInterceptor(options: _defaultCacheOptions),
]);
```
and this

```dart
options: _defaultCacheOptions
    .copyWith(maxAge: const Nullable(Duration(minutes: 5)))
    .toOptions(),
```

Yet I am still of the opinion that the package could be improved if this was inbuilt.

I understand that you do not want to implement arbitrary requests to customize the caching and that adding such an option would be a step into that direction, however, I also feel like overriding the maxAge is a very reasonable and common need. 

I will have to copy this code around in all my packages where I want to replace `dio_http_cache` and cannot simply use the library. 

Perhaps you could reconsider it.

Regardless, I enjoy this package and if we do not get inbuilt support for changing the `maxAge`, there is code for it here now.
