### ISSUE TITLE
Lazy box for hive?

### ISSUE THREAD

**Issue by Reprevise** [llfbandit/dio_cache_interceptor#61]
Right now the HiveStore uses a regular box but Hive also offers a lazy box so that the values aren't read into memory when the box is opened, only the keys are. Sometimes the responses I store are in the 20-30mb range. I like using the Hive store though because I already use it in my app and read/writes are incredibly fast.

It would be nice to be able to pick whether or not the store uses a normal or lazy Hive box.

**Comment by llfbandit** [comment]
Thanks for the report, I didn't know about memory consumption.
Released in 3.1.1
