### ISSUE TITLE
How to handle the cache size of app?

### ISSUE THREAD

**Issue by khurram72** [llfbandit/dio_cache_interceptor#62]
Hi,

Thanks for your amazing package.

So, we have integrated dio cache interceptor with hive store in our app, the caching does work fine.

On startup, the app makes a call to server to get a json file and save it to app directory.

However, the problem we currently facing is, on every app launch the app size is increased by ```4 MB``` , which results in app size getting too large on the disk.

Here's the ```DioCacheInterceptor``` config we are using:

```dart
 DioCacheInterceptor(
          options: CacheOptions(
            store: HiveCacheStore(
              dir.path + "/hive/$version",
              hiveBoxName: "hive_cache",
            ),
            policy: CachePolicy.forceCache,
            hitCacheOnErrorExcept: [401, 403],
            maxStale: const Duration(days: 7),
            priority: CachePriority.normal,
            cipher: null,
            keyBuilder: CacheOptions.defaultCacheKeyBuilder,
            allowPostMethod: false,
          ),
        ),
```

 I did some experimentation & tried calling the clean() on HiveCacheStore object, that does reduces the app size increment factor from ```4 MB``` to  ```1 MB```.

Here's the sample config with clean() method called.

```dart
 DioCacheInterceptor(
          options: CacheOptions(
            store: HiveCacheStore(
              dir.path + "/hive/$version",
              hiveBoxName: "hive_cache",
            )..clean(),
            policy: CachePolicy.forceCache,
            hitCacheOnErrorExcept: [401, 403],
            maxStale: const Duration(days: 7),
            priority: CachePriority.normal,
            cipher: null,
            keyBuilder: CacheOptions.defaultCacheKeyBuilder,
            allowPostMethod: false,
          ),
        ),
```

Could you through some light on how to better handle the increase in app size, due to cache.

Please highlight if there is any scope of improvement in my current approach.

Many Thanks!

**Comment by k00na** [comment]
I'm also experiencing cache file increasing in size each time I manually update HiveCacheStore... it increases the .hive file for cca 400kb each time.
