### ISSUE TITLE
Response interceptors are not called on cache hit

### ISSUE THREAD

**Issue by ezet** [llfbandit/dio_cache_interceptor#64]
I have various interceptors that I need to run regardless of whether it is a cache hit or not, eg. logging and performance tracing interceptors. 

`handler.resolve()` has an argument to handle this, `callFollowingResponseInterceptor` but it defaults to false. `dio_http_cache` uses this mechanism, and it works like a charm, but that library has other issues.

Can you change this argument to true, or make it a configurable option?

**Comment by llfbandit** [comment]
Thanks for the report!
There's no reason to skip other interceptors. I'll do it this weekend.

**Comment by llfbandit** [comment]
Done in v3.2.6

**Comment by leslmosnk** [comment]
Seems like this problem has returned on later versions of dio.
