### ISSUE TITLE
Please make _updateCacheResponse() protected

### ISSUE THREAD

**Issue by slavap** [llfbandit/dio_cache_interceptor#65]
In some cases, I need to create descendants of DioCacheInterceptor and need an ability to override _updateCacheResponse()

**Comment by llfbandit** [comment]
I won't. If you want to tweak the response, please create a following interceptor and access the store directly on your side.

**Comment by slavap** [comment]
@llfbandit it is possible to copy/paste your code and change it, but inheritance is the right way in case of non-significant changes in obvious place. Please reconsider and make updateCacheResponse protected.

**Comment by llfbandit** [comment]
A use case could help to understand why you need to override the interceptor and this method.

**Comment by slavap** [comment]
@llfbandit in my case some headers are changing during time, and these new headers should be returned by cached request s as well. I don’t need/want to clear cache, because cached payload is still correct and it’s size is big, but I need to adjust headers for cached requests on cache hit.

**Comment by llfbandit** [comment]
So you're manually managing your cache. Your origin server doesn't have cache directives.
I would suggest you to directly access your store to update the response if available. It would be more efficient than re-create the request to finally re-create the response.
To explain my point of view, Interceptor class is no API, I can't guarantee that it will last with the current design for a long term.

**Comment by slavap** [comment]
@llfbandit That's what I currently did - implemented my own store. It works just fine, but I don't like that in 
```dart
Future<CacheResponse?> get(String key) async {}
```
I need to decrypt headers, adjust them, and encrypt them again.
