### ISSUE TITLE
Benefits over dio_http_cache?

### ISSUE THREAD

**Issue by netlob** [llfbandit/dio_cache_interceptor#67]
Hi,

I'm integrating a memory only dio cache in my app and was wondering if there are any benefits of using this package over https://pub.dev/packages/dio_http_cache ?

Thanks in advance,
Sjoerd

**Comment by llfbandit** [comment]
It really depends of your needs.
[dio_http_cache](https://pub.dev/packages/dio_http_cache) seems not maintained, does not respect HTTP cache directives and depends on useless dependencies for memory storage.
