### ISSUE TITLE
Bug: return data from cache if there is a socket exception with hitCacheOnErrorExcept option.

### ISSUE THREAD

**Issue by NamanShergill** [llfbandit/dio_cache_interceptor#7]

**Comment by llfbandit** [comment]
Already available with hitCacheOnErrorExcept

**Comment by NamanShergill** [comment]
> 
> 
> Already available with hitCacheOnErrorExcept

That's the issue, it doesn't work.

https://github.com/llfbandit/dio_cache_interceptor/blob/c0c923c3c7cdb182a2f9044bf53d789b32a96115/lib/src/dio_cache_interceptor.dart#L115
The package is only checking the hitCacheOnErrorExcept parameter if the error.response is not null, which it would be on a socket exception, so it never returns the cached data.

**Comment by llfbandit** [comment]
Oups, yes thanks for the report.

**Comment by llfbandit** [comment]
Fixed in eb653b15.
Still need to add proper test.

**Comment by llfbandit** [comment]
Fixed in rc1
