### ISSUE TITLE
Calling a API method multiple times with encryption

### ISSUE THREAD

**Issue by AustrianDudes** [llfbandit/dio_cache_interceptor#70]
Hi,
I have currently added an AES encryption to an HiveCacheStore and am experiencing a weird issue. 

1. When I call the API method the first time, it loads the data properly from the web and stores it. 
2. When I call the method the second time, it loads the data properly from the store, decrypts it and returns it. 
3. When I call the method the third time in a row, it tries to decrypt the stored data, but fails at it (as the bytes passed to the decryption method seems to have been already decrypted). 
Has anybody any inside on how to fix or work around this issue?

Kind regards, 
Pierre

**Cache cipher:**
`cipher: CacheInterceptor.CacheCipher(encrypt: (bytes) async {
  return _encrypter.encryptBytes(bytes, iv: _initVector).bytes;
}, decrypt: (bytes) async {
  return _encrypter.decryptBytes(Encrypted(Uint8List.fromList(bytes)), iv: _initVector);
}),`

**Second call:**
`I/flutter (14072): │ Encrypted data: .ڀ�O�....`
`I/flutter (14072): │ Decrypted data: [{"id":"cs_test_cdc6f02c-b0ea-412b-b6fb-83b5db51f473",...}]`

**Third call:**
`I/flutter (14072): │ Encrypted data: [{"id":"cs_test_cdc6f02c-b0ea-412b-b6fb-83b5db51f473",...}]`
`I/flutter (14072): [2022-04-04 13:53:07| Catcher] Invalid argument(s): Input data length must be a multiple of cipher's block size`
`I/flutter (14072): [2022-04-04 13:53:07| Catcher] ------- STACK TRACE -------`
`I/flutter (14072): [2022-04-04 13:53:07| Catcher] #0      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:60:9)`
`I/flutter (14072): [2022-04-04 13:53:07| Catcher] #1      AES.decrypt (package:encrypt/src/algorithms/aes.dart:63:22)`
`I/flutter (14072): [2022-04-04 13:53:07| Catcher] #2      Encrypter.decryptBytes (package:encrypt/src/encrypter.dart:25:17)`

**Comment by AustrianDudes** [comment]
Hi,
Thanks for your response. I can confirm that we use `CacheInterceptor.CachePolicy.request` policy for the cache options we use for all three requests.

Okay that's a great hint, I'll look into that.
kind regards

**Comment by llfbandit** [comment]
This is now fixed in 3.2.7
