### ISSUE TITLE
Caching Specfic Endpoints

### ISSUE THREAD

**Issue by nathanielgreen** [llfbandit/dio_cache_interceptor#71]
Hey I was wondering if it's possible to Cache only a specific endpoint use this package and not cache all requests? I've looked through the code and documentation but it's not entirely clear if this is possible or how to go about it.

**Comment by llfbandit** [comment]
Yes, you can do that with the policy directives.

For example, if only few endpoints should be skipped, you can set `CachePolicy.request` as a global behaviour (which is the default by the way) and setup the remaining endpoints to skip cache like :
```dart
response = await dio.get('https://www.foo.com',
  options: globalOptions.copyWith(policy: CachePolicy.noCache).toOptions(),
);
```

**Comment by nathanielgreen** [comment]
Ah I see, is it possible to add this at an interceptor level rather than at the request level? For example I'm attempting to add the interceptor to a package class that exposes it's Dio instance, but the request code itself cannot be modified.

I imagine something like this (pseudocode):

```dart
  dioInstance..interceptors.add(InterceptorsWrapper(
    onRequest: (RequestOptions options, handler) {
      if (options.uri.toString().contains('<uri_to_cache_here>')) {
        return handler.next(_cacheOptions.copyWith(policy: CachePolicy.forceCache).toRequestOptions());
      }
      return handler.next(options);
    },
  ));
```

**Comment by llfbandit** [comment]
Yes absolutely, just be careful to always call `handle.next()` in the three callbacks.

**Comment by nathanielgreen** [comment]
Sorry if I wasn't clear, the above is actually pseudo-code and wouldn't work as there is no `toRequestOptions()`. Using `toOptions()` in this case also wouldn't work as it isn't of type `RequestOptions`.

Do you know of a way of writing this kind of request in the format above using the cache options?

**Comment by llfbandit** [comment]
I guess you could achieve this by simply overriding the extra by doing something like this:
```dart
if (options.uri.toString().contains('<uri_to_cache_here>')) {
  final cacheOptions = CacheOptions.fromExtra(options);
  options.extra.addAll(cacheOptions.copyWith(policy: CachePolicy.forceCache).toExtra());
}
return handler.next(options);
```

**Comment by nathanielgreen** [comment]
> I guess you could achieve this by updating the extra with something like this:
> 
> ```dart
> if (options.uri.toString().contains('<uri_to_cache_here>')) {
>   final cacheOptions = CacheOptions.fromExtra(options);
>   options.extra.addAll(cacheOptions.copyWith(policy: CachePolicy.forceCache).toExtra());
> }
> return handler.next(options);
> ```
> 
> extra is a `Map<String, dynamic>` so `addAll` will update the `CacheOptions` underlying key without making any noise around.

Sorry about the slow reply, this worked great! Thanks so much!
