### ISSUE TITLE
Receive fresh data after the cached data is returned

### ISSUE THREAD

**Issue by diegoveloper** [llfbandit/dio_cache_interceptor#73]
Thanks for this great package, I have some questions about the usage.
I was checking the cache policy ->  `CachePolicy.forceCache` and : 

- When I do the first call it retrieves the data from server and cache data. 
- Now when I do the same call , It retrieves the cached-data(which is fine) and I suppose it's refreshing the cached data from server, right? 
-  Is there any way to , receive the cached-data , fetch the server to refresh the cache and after that emit the new data? (I'm talking about something like a stream that we can use)

Manual work, should be:

- Call the api and return a Stream with data.
- Check the status, if the status is 304, then get a fresh data , wait until it's loaded and emit the new data to the stream.

is there any callback to know if the data was refreshed/updated? `dio.get(url, options: options)`

**Comment by llfbandit** [comment]
If your server has cache directives, you should never use `CachePolicy.forceCache`.

Otherwise, status code should be enough to determine if the content is from cache or not.
Also, there's an additional data in response extra: you could check against `CacheResponse.fromNetwork` boolean value.

**Comment by llfbandit** [comment]
No there's no callback, only the filled response.
Just wrap your calls with the custom checks and push events to the stream when getting desired result.

**Comment by diegoveloper** [comment]
> No there's no callback, only the filled response. Just wrap your calls with the custom checks and push events to the stream when getting desired result.

Can you give me some hints? 

How could you do this:  

- Get data from cache first.
- If there is no cache data, get from server and cache the data.
- Next time, Get data from cache and also fetch the data from server in order to refresh the cache.
- how can we know this -> The data from server is received and the cache updated.

**Comment by llfbandit** [comment]
If your server has no cache directives, which seems to be the case, you are the only one about to get the answer.

You can access directly to your store and manipulate data from it with simple API (get, set, ...).
Here's a minimal sample for store manipulation:

```dart
CacheOptions options = ...;
final cacheKey = options.keyBuilder(request); 
await options.store.delete(cacheKey);
```

**Comment by diegoveloper** [comment]
thanks for you answer :)
