### ISSUE TITLE
how can i do this:

### ISSUE THREAD

**Issue by zystudios** [llfbandit/dio_cache_interceptor#74]
When online, read always from network and cache result.
When offline, (or bad request，403 500 503...), read from cache.

thanks

**Comment by llfbandit** [comment]
policy: CachePolicy.request, or forceCache, 
hitCacheOnErrorExcept: [401, 403, ...],

**Comment by zystudios** [comment]
> policy: CachePolicy.request, or forceCache, hitCacheOnErrorExcept: [401, 403, ...],

Thanks for your reply, in my simulator (ios or android), I'm already connected to the Internet, but it will not make new requests, it always read from the cache (I don't see any requests sent in the network tools)

This causes my server data to be updated, but the client's data is still old

 
```
CacheOptions(
      store: FileCacheStore("${appDocPath}/cache"),
      policy: CachePolicy.forceCache,
      hitCacheOnErrorExcept: [401, 403, 500, 503],
      maxStale: const Duration(days: 7),
      priority: CachePriority.normal,
      cipher: null,
      keyBuilder: CacheOptions.defaultCacheKeyBuilder,
      allowPostMethod: false,
    );
```

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0 21A344 darwin-arm)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

@llfbandit  Thanks
