### ISSUE TITLE
Cache clearing strategy for Hive cache

### ISSUE THREAD

**Issue by rubenvereecken** [llfbandit/dio_cache_interceptor#75]
Finally, etags! Great job on this by the way.

I was reading your hive cache implementation and I didn't see anything that would clean old values (according to `max-age`). For example, I checked where `isExpired` was used, and it was only in one place. Is this implemented? I'm worried about over-crowding the cache over time. 

Thanks!

**Comment by llfbandit** [comment]
Store packages do nothing by themselves. All the logic is located in the interceptor.
Expired cache entries are removed when interceptor is started and when a key is read and elected as such.

**Comment by rubenvereecken** [comment]
So I did read it right. The only way for an expired entry to be removed is when there's an attempt to read it. But what if it never gets read again?

Take the arbitrary example where you have many news articles, and you'd fetch one with `GET /news/:id`. You might never see old news again, so you'd never hit that news id again (eg `GET /news/12`), meaning (I think) that old news entries will stick around forever. That could build up quite quickly.

Off the top of my head, would it be possible to have something like a garbage cleaning cycle? Every so often old entries could be checked against their associated max-age and removed if applicable.

**Comment by rubenvereecken** [comment]
You're absolutely right, I missed the part about "when the interceptor is started". Thanks @llfbandit !
