### ISSUE TITLE
Ability to cache some requests with pattern

### ISSUE THREAD

**Issue by Siqlain-Hanif** [llfbandit/dio_cache_interceptor#76]
I have some POST requests with specific pattern in the URL that i want to cache and ignore other. I think currently we cant do that. 

My suggestion is to add an ability to add the URL regex pattern that will ignore the methods and see if this pattern matches then cache the response if not fallback to the current cache trigger implementation.

**Comment by llfbandit** [comment]
For specific caching strategy you can do something like this:
```dart
  dioInstance..interceptors.add(InterceptorsWrapper(
    onRequest: (RequestOptions options, handler) {
      if (regex.hasMatch(${options.uri}')) {
        return handler.next(_cacheOptions.copyWith(policy: CachePolicy.forceCache).toRequestOptions());
      }
      return handler.next(options);
    },
  ));
```

**Comment by Siqlain-Hanif** [comment]
@llfbandit That's what i needed. Thanks.
