### ISSUE TITLE
forceCache will never expire when the interval between each response is less than maxStale

### ISSUE THREAD

**Issue by Huzhengtao** [llfbandit/dio_cache_interceptor#78]
I only use client control cache. but CachePolicy.forceCache will update cached data with cached data if the interval less than maxStale.It doesn't make sense. maxStale should calculate the time interval from the first request time to the present

**Comment by Huzhengtao** [comment]
I found that when the cache data is hit, the status code will be set to 304 by the client (not server 304), which reacts with #5

**Comment by llfbandit** [comment]
`CachePolicy.forceCache` will force to cache. What do you expect other than this?
Also, the issue you mentioned is not related.

**Comment by Huzhengtao** [comment]
ok,it seems not suit for only client caching . I can't use CachePolicy.request because the client controls all caches , so CachePolicy.forceCache is the only choose , but it did not perform as expected . could you consider add a only client control mode?

**Comment by llfbandit** [comment]
I just made a simple wiki page to illustrate how to handle cache with client side only since this is a reccuring issue.
https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only

First sample should prettry much suits your needs.

**Comment by Huzhengtao** [comment]
fine, thank you very much for your answer

**Comment by Abushawish** [comment]
@llfbandit I'm not sure I understand the wiki. 

What's the `cacheOptions`? Is it an instance of CacheOptions or the CacheOptions class? 

What about `request`? 

Or `store.get`, is that some kind of SharedPrefs call? 

Or `cache`? What's that class? 

Would it make sense to add the ability for the forceCache not to overwrite the cache expiration time when the cache itself got reused? I feel like it makes more sense for forceCache to only reset the cache when it gets fresh non-cached data. Thoughts?

Thanks so much.

**Comment by Huzhengtao** [comment]
@Abushawish if you don't use HTTP Cache-Control Directives , try [[dio_http_cache](https://pub.dev/packages/dio_http_cache)]
