### ISSUE TITLE
CacheStore in CacheOptions should be required instead of nullable considering the interceptor asserts it not being null when it is used.

### ISSUE THREAD

**Issue by NamanShergill** [llfbandit/dio_cache_interceptor#8]

**Comment by NamanShergill** [comment]
Unless I missed something and it is being used somewhere else where it can be nullable. Apologies in advance if that is the case!

**Comment by llfbandit** [comment]
No problem, this is to allow other stores on dedicated requests in same dio instance.
I'll make it `required` to limit mistakes.
