### ISSUE TITLE
Code example for "Handling cache with client only"

### ISSUE THREAD

**Issue by yh-luo** [llfbandit/dio_cache_interceptor#80]
Hi,

Thanks for the brilliant package!
I followed the Wiki to handle caches from the client side and notice the discrepancy from the example and the real case.
To return the `Response` dirrectly, we should use `handler.resolve`. Also `request` is not defined in the context, it should be `options`.

The working example would be:
```dart
dioInstance..interceptors.add(InterceptorsWrapper(
  onRequest: (RequestOptions options, handler) {
    final key = cacheOptions.defaultCacheKeyBuilder(request);

    final cache = await store.get(key);
    if (cache != null && DateTime.now().difference(cache.responseDate).inMinutes < 5) {
      return handler.resolve(cache.toResponse(options, fromNetwork: false));
    }

    return handler.next(options);
  },
));
```
Hope this help!

**Comment by llfbandit** [comment]
Thanks for the report. It is now fixed.
