### ISSUE TITLE
getAll saved CacheResponse from CacheStore

### ISSUE THREAD

**Issue by clragon** [llfbandit/dio_cache_interceptor#81]
For some manual labour purposes it would be very useful 
to be able to get a list of all saved `CacheResponse` objects that currently reside in the store. 
(`Future<List<CacheResponse>> getAll()`)

As an example, #9 could be solved from outside the package, if the entries where accessible.

Another thing I am facing right now is that I am migrating from `dio_http_cache` 
which allowed me to use primary and subkeys for my cached data. 
This was useful to delete the cache for an API call that included a `page=i` in its URL.
I cannot strip the page from the URL, because then I would get the latest page for all pages, but I need to be able to delete all cached pages for a particular endpoint. 

I could implement this logic myself as well, if I had access to all `CacheResponse` entries.

**Comment by clragon** [comment]
I see. I briefly considered the possiblity of this being very expensive, and then chose that it might be fine, because some store implementations are in memory, so how large could they possibly become. But I definitely see the problem.

Having some sort of query for the responses would be a great way of reducing the cost of specific searches, if theyre feasible to implement in all stores (which I wasnt sure of, which is why I didnt propose it).
The method you have proposed definitely seems like it could solve my issue.

**Comment by llfbandit** [comment]
Available now in version 3.3.0.

**Comment by clragon** [comment]
thank you very much!
I will try it out as soon as I have time. 

(though from a quick glance at the code, wouldn't
https://github.com/llfbandit/dio_cache_interceptor/blob/master/dio_cache_interceptor_db_store/lib/src/store/dio_cache_interceptor_db_store.dart#L86
have to be awaited for this to work?)

**Comment by llfbandit** [comment]
I guess you're right, I'll fix this end of July.
