### ISSUE TITLE
HiveCacheStorage saves so much reducant NUL data

### ISSUE THREAD

**Issue by xVemu** [llfbandit/dio_cache_interceptor#84]
When I launch an app for the first time, the data is being saved correctly. File with cache weights about 2 KB. But when I launch the app again, with cache this time, then HiveCacheStorage saves some weird data to the Hive cache file like this in the picture below.

![image](https://user-images.githubusercontent.com/38427679/185364529-a0e8e681-2b96-4aec-ab83-fca443e66980.png)

It repeats every time I launch the app, and the cache file is growing like 15 KB per launch, when JSON weights about 2 KB.

<details>
  <summary>Code sample</summary>

  ```dart
final options = CacheOptions(
        store: HiveCacheStore(null),
        maxStale: Duration(days: 1),
        policy: CachePolicy.forceCache,
      );
      final dio = Dio()
        ..interceptors.add(DioCacheInterceptor(options: options));

      (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
          (HttpClient dioClient) {
        dioClient.badCertificateCallback =
            ((X509Certificate cert, String host, int port) => true);

        return dioClient;
      };

      var response = await dio.get(
          "https://api.nasa.gov/planetary/apod?api_key=RAarp1XLTlplmQ0FywIKKAXcVbUHkinYmRYB9tYl");
      print(response.data);
```
</details>

**Comment by llfbandit** [comment]
Thanks for the report, this is expected.
Hive stores data in a single file with an append-only behaviour for performance, this is why you get those NULL values.
At some time, Hive will automatically compact it to not take more than it should.

The default strategy given by Hive is this [one](https://github.com/hivedb/hive/blob/master/hive/lib/src/box/default_compaction_strategy.dart).

**Comment by xVemu** [comment]
Oh, I didn't expect that. Thanks for answer!
