### ISSUE TITLE
[dio_cache_interceptor_db_store] upgrade to drift 2

### ISSUE THREAD

**Issue by clragon** [llfbandit/dio_cache_interceptor#85]
drift has updated its major version to [2](https://drift.simonbinder.eu/docs/upgrading/), coming with alot of nice improvements in terms of null safety.
it would be great if we had db_store also upgraded to drift 2 so we can use it while also using the latest drift version.

**Comment by llfbandit** [comment]
dio_cache_interceptor_db_store 5.0.0 available for the upgrade.

**Comment by clragon** [comment]
lovely, thank you!
