### ISSUE TITLE
Cannot return cache without network

### ISSUE THREAD

**Issue by liuguicen** [llfbandit/dio_cache_interceptor#86]
I need to return the cache when there is no network or network error, but I can't get the cache using the following configuration, and always report an error。There are my code。
``` dart
  static final CacheOptions baseCacheOptions = CacheOptions(
    // A default store is required for interceptor.
    store: MemCacheStore(
        maxSize: 32 * 1024 * 1024,
        // 单条数据最大值
        maxEntrySize: 2 * 1024 * 1024),

    // All subsequent fields are optional.

    // Default.
    policy: CachePolicy.forceCache,
    // 设置哪些情况不返回缓存，比如没有网络
    // [401, 403] 授权或者认证失败
    // hitCacheOnErrorExcept: [401, 403],

    // 缓存时间
    maxStale: const Duration(days: 7),
    // Default. Allows 3 cache sets and ease cleanup.
    priority: CachePriority.normal,
    // 加密 Default. Body and headers encryption with your own algorithm.
    cipher: null,
    // 允许post，允许post 必须重写 keyBuilder
    allowPostMethod: true,
    // 构造请求缓存项的key
    // keyBuilder: CacheOptions.defaultCacheKeyBuilder,
    keyBuilder: (RequestOptions request) {
      Map paramForCache = {}
        ..addAll(request.queryParameters)
        ..remove(Backend.appVersion)..remove(Backend.channel);
      return _uuid.v5(Uuid.NAMESPACE_URL,
          request.uri.toString() + json.encode(paramForCache));
    },
  );

```

**Comment by llfbandit** [comment]
Un-comment `hitCacheOnErrorExcept: []`.
Add status codes in the collection to not return cache from them. All network errors are returned when missing response.

**Comment by liuguicen** [comment]
My operation is to open the network and request data successfully
Turn off network hot overload and re request data
Then I went into debugging and found that the data here was empty
![2022-08-24 04-26-12 的屏幕截图](https://user-images.githubusercontent.com/13100498/186258985-189d28fa-a25b-4c71-bfa3-94f3f2917cd9.png)

Is there any operation that causes the cache to be emptied, or do I need to read the cache with code first

**Comment by llfbandit** [comment]
hot overload ???
If you restart your app, memory is cleared. `MemCacheStore` is made for ephemeral storage.

**Comment by liuguicen** [comment]
Oh, oh, I see. Sorry, I didn't notice this
I just followed the example code and thought it would be cached on disk
So what tools do I use for persistent caching

**Comment by llfbandit** [comment]
Store list is in the readme.md. Choose which suits best your needs.
