### ISSUE TITLE
pathExists queryParams are not checked correctly

### ISSUE THREAD

**Issue by clragon** [llfbandit/dio_cache_interceptor#87]
There seem to be some issues with the way `CacheStore.pathExists` handles the `queryParams` parameter
which does not match the documented behaviour.
As of right now, I get no matches for my query params.

The current implementation is:
```dart
    if (queryParams != null) {
      for (final entry in queryParams.entries) {
        hasMatch &= (!uri.queryParameters.containsKey(entry.key));
        if (entry.value != null) {
          hasMatch &= !uri.queryParameters.containsValue(entry.value);
        }
        if (!hasMatch) break;
      }
    }
```

- both of the conditions are inverted?
- the `entry.value` is checked against _all_ values, instead of just the `key` it belongs to.

a potential fix would look something like this:
```dart
    if (queryParams != null) {
      for (final entry in queryParams.entries) {
        hasMatch &= uri.queryParameters.containsKey(entry.key);
        if (entry.value != null) {
          hasMatch &= uri.queryParameters[entry.key] == entry.value;
        }
        if (!hasMatch) break;
      }
    }
```

**Comment by llfbandit** [comment]
Thanks, I agree with the proposal.
Could you fill a PR with tests? I rushed before leaving on vacation and I'm a bit overhelmed right now.

**Comment by clragon** [comment]
I have made a PR with tests. 
first time I have ever written tests. 
please let me know if there need to be any changes.

**Comment by llfbandit** [comment]
I expected tests on stores also but that's fine. Planning this to be released later this day or tomorrow.
Thanks for your help.

**Comment by clragon** [comment]
well the `pathExists` function isnt overriden in any of the stores so I thought it would be repetitive to test it in all stores separately.

**Comment by llfbandit** [comment]
Sorry, I was unclear, I thought about `deleteFromPath` and `getFromPath` methods.

**Comment by llfbandit** [comment]
Now published
