### ISSUE TITLE
Questions about 'maxStale'

### ISSUE THREAD

**Issue by gjrjf** [llfbandit/dio_cache_interceptor#89]
hello.
First of all, thank you for making such a great plugin.

I have a question.

**1. The header response of the server is as follows.**
cache-control: no-cache, no-store, max-age=0, must-revalidate

**2. I used the following cache option:**
```
final cacheOptions = CacheOptions(
       store: cacheStore, // memory
       maxStale: Duration(seconds: 5),
       policy: CachePolicy.forceCache
     );
```

**3. Here is the result.**
  - CachePolicy.forceCache : Cache forever unless the app is closed.
  - CachePolicy.refreshForceCache : Not cached.

What I meant is that even if the server gives a no-cache response
Locally throttling the cache time according to 'maxStale'.

Am I using it wrong?
Any advice would be appreciated.

**Comment by llfbandit** [comment]
Your answer is [here](https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only).
