### ISSUE TITLE
cache not working

### ISSUE THREAD

**Issue by water-user** [llfbandit/dio_cache_interceptor#91]
I copy paste the snippet code from the package page (https://pub.dev/packages/dio_cache_interceptor) and the request always return status code of 200, why?
There's a eTag of course:
![Screen Shot 2022-09-01 at 13 06 51](https://user-images.githubusercontent.com/95235346/187889822-5134da3f-e5ec-4f1e-83f3-3d21e272524c.png)
![Screen Shot 2022-09-01 at 13 06 08](https://user-images.githubusercontent.com/95235346/187889819-39d2b1f0-04f9-4415-a0d3-66558f5f6cd0.png)

**Comment by llfbandit** [comment]
The issue is not filled with all info, so I can't be sure about the context.
Does your origin really handle cache directives? You can try to re-use your etag with an external HTTP client.

**Comment by water-user** [comment]
"Does your origin really handle cache directives" I didn't understand what you mean.

I try with this link https://avatars.githubusercontent.com/u/95235346?s=52&v=4 and it's working, It's return 304.

I tried with my own server on external http, and it's not working, always return status 200, but in the browser it's working and return me 304 after the first loading.

Here's the full code
```
import 'package:dio/dio.dart';
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart';

class MyDio {
  static late Dio dio;

  static final options = CacheOptions(
    // A default store is required for interceptor.
    store: MemCacheStore(),

    // All subsequent fields are optional.

    // Default.
    policy: CachePolicy.request,
    // Returns a cached response on error but for statuses 401 & 403.
    // Also allows to return a cached response on network errors (e.g. offline usage).
    // Defaults to [null].
    hitCacheOnErrorExcept: [401, 403],
    // Overrides any HTTP directive to delete entry past this duration.
    // Useful only when origin server has no cache config or custom behaviour is desired.
    // Defaults to [null].
    maxStale: const Duration(days: 7),
    // Default. Allows 3 cache sets and ease cleanup.
    priority: CachePriority.normal,
    // Default. Body and headers encryption with your own algorithm.
    cipher: null,
    // Default. Key builder to retrieve requests.
    keyBuilder: CacheOptions.defaultCacheKeyBuilder,
    // Default. Allows to cache POST requests.
    // Overriding [keyBuilder] is strongly recommended when [true].
    allowPostMethod: false,
  );

// Add cache interceptor with global/default options
  static initDio() async {
    dio = Dio()..interceptors.add(DioCacheInterceptor(options: options));
    final String url = 'http://10.0.2.2/channels/getChannels';
    final result1 = await dio.get(url);
    print(result1);
    final result2 = await dio.get(url);
    print(result2);
  }
}
```

**Comment by llfbandit** [comment]
Depending of the content, web browsers may cache aggressively some resources like CSS, java scripts, images, ...
So, from my point of view, there is no issue with the package. You'll need to setup cache on server side to complete the workflow.

**Comment by xOldeVx** [comment]
Let me understand.. dio not cache JSON content??

**Comment by llfbandit** [comment]
This not how HTTP cache works no.
Dio is just a client which will transport data over network (to say this short).
`dio_cache_interceptor` adds client cache capabilities but the server needs to be compliant too.
In short, HTTP cache is made with two parts, client AND server. The package can handle some usecases for client cache only but it's another topic. [Some hints here](https://github.com/llfbandit/dio_cache_interceptor/wiki/Handling-cache-with-client-only).

**Comment by water-user** [comment]
My server is return etag as you can see in the first screenshot.
What i miss?

**Comment by llfbandit** [comment]
As you mentionned, the origin server still returns a complete reponse with code 200 (likely with full content) and confirmed by your external call.
If your content is not of the types mentioned above try to redo what your browser send by default.
Mostly cache-control header. Maybe Express expect something which isn't given by default by the interceptor (interceptor should already provide cache-control header but...).

**Comment by water-user** [comment]
As you can see in the screenshot the browser mange the request automatic by the **etag**, that's why i can't understand why the package not mange it automatic by the **etag** like the browser, what's wrong?
![image](https://user-images.githubusercontent.com/95235346/188070849-ffc45b3e-956c-4315-b346-d9561f95ec6d.png)

Here's the response in the browser
![image](https://user-images.githubusercontent.com/95235346/188071151-87de82bf-5ded-4c78-8144-28cc51c31b86.png)

**Comment by llfbandit** [comment]
Try with enforcing `Cache-Control` to `max-age=0`
