### ISSUE TITLE
FileCacheStore.getFromPath finishes before the return value has been populated

### ISSUE THREAD

**Issue by JordanMarshall** [llfbandit/dio_cache_interceptor#92]
Calling `getFromPath` on a FileCacheStore returns an empty list, even when there are matching cached responses.

As far as I can tell this is due to the use of `.forEach` with `async` here, which results in `getFromPath` returning before the responses list has been populated: https://github.com/llfbandit/dio_cache_interceptor/blob/27b6b9107d2489b0e9b3dfb5ffc50f0590900db1/dio_cache_interceptor_file_store/lib/src/store/dio_cache_interceptor_file_store_io.dart#L88

Swapping that line out with the following line appears to fix the issue for me:
`await Future.forEach(directory.listSync(followLinks: false), (fse) async {`

I noticed a similar pattern being used in the `clean` method, so it's possible that method is also returning before all files have been deleted:
https://github.com/llfbandit/dio_cache_interceptor/blob/27b6b9107d2489b0e9b3dfb5ffc50f0590900db1/dio_cache_interceptor_file_store/lib/src/store/dio_cache_interceptor_file_store_io.dart#L29

**Comment by llfbandit** [comment]
Thanks for the report.
Both methods have been reworked. Available in v1.2.1.
