### ISSUE TITLE
How to fetch from cache if available but still load from network in background?

### ISSUE THREAD

**Issue by xVemu** [llfbandit/dio_cache_interceptor#93]
Same question like hurshi/dio-http-cache#58, but for this package. Is it possible?

**Comment by llfbandit** [comment]
I don't see how useful it could be.
What would happen if the fresh data is different from the cache? You'll serve wrong data....
What would happen if the request has failed? You'll serve wrong data... 

I suppose you need to handle cache from client only. If so, look at the wiki to implement such case by yourself by wrapping the interceptor and add your own logic.
