### ISSUE TITLE
Ensure drift database isolate is closed

### ISSUE THREAD

**Issue by clragon** [llfbandit/dio_cache_interceptor#97]
following up on #94:
in older drift versions, isolates must be explicitly closed.
however, I have asked upstream to implement an easy feature to close isolates when the single connection is closed.
by upgrading to drift 2.3.0 we can take advantage of this and shorten the isolate code by alot,
and make sure that users to not run into lingering database connections.

**Comment by llfbandit** [comment]
This merge has not been published yet because `open.overrideFor` is not honored when using `createBackgroundConnection`.

**Comment by llfbandit** [comment]
`open.overrideFor` is used to set the path of the sqlite library to load when opening the connection. Tests on the package are tied to this (I'm on Windows platform).

**Comment by clragon** [comment]
I see. should we report this as a bug to drift?

**Comment by clragon** [comment]
I have investigated, and I dont quite understand why we need `open.overrideFor` and the `sqlite3` library. 
I have removed both and the tests run through. 🤔
